package net.ilexiconn.jurassicraft.client.model.entity;

import net.ilexiconn.jurassicraft.client.model.animation.Animator;
import net.ilexiconn.jurassicraft.client.model.base.MowzieModelBase;
import net.ilexiconn.jurassicraft.client.model.base.MowzieModelRenderer;
import net.ilexiconn.jurassicraft.common.api.IAnimatedEntity;
import net.ilexiconn.jurassicraft.common.entity.dinosaurs.EntityApatosaurus;
import net.minecraft.world.entity.Entity;
import net.minecraftforge.api.distmarker.Dist;
import net.minecraftforge.api.distmarker.OnlyIn;

@OnlyIn(Dist.CLIENT)
public class ModelApatosaurus extends MowzieModelBase {

   public Animator animator = new Animator(this);
   MowzieModelRenderer body;
   MowzieModelRenderer toplegleft;
   MowzieModelRenderer toplegright;
   MowzieModelRenderer neck1;
   MowzieModelRenderer Stomach;
   MowzieModelRenderer hips;
   MowzieModelRenderer frontlefttopleg;
   MowzieModelRenderer frontrighttopleg;
   MowzieModelRenderer neck2;
   MowzieModelRenderer neck3;
   MowzieModelRenderer neck4;
   MowzieModelRenderer neck5;
   MowzieModelRenderer neck6;
   MowzieModelRenderer head;
   MowzieModelRenderer snout;
   MowzieModelRenderer jaw;
   MowzieModelRenderer tail1;
   MowzieModelRenderer tail2;
   MowzieModelRenderer tail3;
   MowzieModelRenderer tail4;
   MowzieModelRenderer tail5;
   MowzieModelRenderer tail6;
   MowzieModelRenderer bottomfrontleftleg;
   MowzieModelRenderer frontleftfoot;
   MowzieModelRenderer bottomfrontrightleg;
   MowzieModelRenderer frontrightfoot;
   MowzieModelRenderer bottomlegleft;
   MowzieModelRenderer leftbackfoot;
   MowzieModelRenderer bottomlegright;
   MowzieModelRenderer rightbackfoot;
   MowzieModelRenderer[] neckParts;
   MowzieModelRenderer[] tailParts;


   public ModelApatosaurus() {
      this.textureWidth = 512;
      this.textureHeight = 512;
      this.neck6 = new MowzieModelRenderer(this, 39, 86);
      this.neck6.setRotationPoint(0.0F, -3.2F, -4.9F);
      this.neck6.addBox(-3.0F, -0.3F, -21.0F, 6, 5, 5, 1.0F);
      this.setRotateAngle(this.neck6, 0.23404865F, -0.0F, 0.0F);
      this.tail6 = new MowzieModelRenderer(this, 94, 276);
      this.tail6.setRotationPoint(0.0F, 0.7040436F, 18.755116F);
      this.tail6.addBox(-2.5F, 0.0F, 0.0F, 5, 5, 22, 0.0F);
      this.setRotateAngle(this.tail6, 0.0837758F, 0.0F, 0.0F);
      this.bottomlegleft = new MowzieModelRenderer(this, 230, 40);
      this.bottomlegleft.setRotationPoint(0.0F, 17.951286F, 0.036030103F);
      this.bottomlegleft.addBox(-3.0F, 0.0F, 0.0F, 7, 19, 7, 0.0F);
      this.setRotateAngle(this.bottomlegleft, 0.4029965F, 0.0F, 0.0F);
      this.leftbackfoot = new MowzieModelRenderer(this, 230, 70);
      this.leftbackfoot.setRotationPoint(0.0F, 18.919096F, 6.9905515F);
      this.leftbackfoot.addBox(-3.0F, 0.0F, -7.0F, 7, 8, 7, 0.0F);
      this.setRotateAngle(this.leftbackfoot, -0.17627825F, 0.0F, 0.0F);
      this.tail1 = new MowzieModelRenderer(this, 94, 95);
      this.tail1.setRotationPoint(0.0F, -0.4002783F, 10.605608F);
      this.tail1.addBox(-8.0F, 0.0F, 0.0F, 16, 17, 13, 0.0F);
      this.setRotateAngle(this.tail1, -0.098262034F, 0.0F, 0.0F);
      this.frontleftfoot = new MowzieModelRenderer(this, 200, 50);
      this.frontleftfoot.setRotationPoint(0.0F, 12.854573F, -3.001658F);
      this.frontleftfoot.addBox(-3.5F, 0.0F, 0.0F, 6, 6, 6, 0.0F);
      this.setRotateAngle(this.frontleftfoot, 0.2003638F, 0.0F, 0.0F);
      this.neck5 = new MowzieModelRenderer(this, 48, 104);
      this.neck5.setRotationPoint(0.0F, 4.1F, -8.6F);
      this.neck5.addBox(-3.0F, 0.0F, -21.0F, 6, 6, 10, 1.0F);
      this.setRotateAngle(this.neck5, -0.29513517F, -0.0F, 0.0F);
      this.tail4 = new MowzieModelRenderer(this, 94, 213);
      this.tail4.setRotationPoint(0.0F, 1.0232527F, 12.767261F);
      this.tail4.addBox(-3.5F, 0.0F, 0.0F, 7, 10, 17, 0.0F);
      this.setRotateAngle(this.tail4, 0.06422812F, 0.0F, 0.0F);
      this.toplegright = new MowzieModelRenderer(this, 230, 0);
      this.toplegright.mirror = true;
      this.toplegright.setRotationPoint(-10.5F, -18.9F, 11.0F);
      this.toplegright.addBox(-4.0F, 0.0F, 0.0F, 9, 21, 10, 0.0F);
      this.setRotateAngle(this.toplegright, -0.22671828F, -0.0F, 0.0F);
      this.frontlefttopleg = new MowzieModelRenderer(this, 200, 0);
      this.frontlefttopleg.setRotationPoint(10.0F, 8.917391F, -17.014116F);
      this.frontlefttopleg.addBox(-5.0F, 0.0F, -5.0F, 7, 14, 7, 0.0F);
      this.setRotateAngle(this.frontlefttopleg, -0.07417649F, 0.0F, 0.0F);
      this.jaw = new MowzieModelRenderer(this, 0, 74);
      this.jaw.setRotationPoint(0.5F, 2.7F, -1.8F);
      this.jaw.addBox(-2.0F, -1.6F, -6.8F, 4, 2, 7, 1.0F);
      this.setRotateAngle(this.jaw, -0.030717796F, -0.0F, 0.0F);
      this.bottomfrontleftleg = new MowzieModelRenderer(this, 200, 30);
      this.bottomfrontleftleg.setRotationPoint(-1.0F, 11.97559F, -0.91391456F);
      this.bottomfrontleftleg.addBox(-3.5F, 0.0F, -3.0F, 6, 13, 6, 0.0F);
      this.setRotateAngle(this.bottomfrontleftleg, -0.31817353F, 0.0F, 0.0F);
      this.toplegleft = new MowzieModelRenderer(this, 230, 0);
      this.toplegleft.setRotationPoint(10.5F, -18.9F, 11.0F);
      this.toplegleft.addBox(-4.0F, 0.0F, 0.0F, 9, 21, 10, 0.0F);
      this.setRotateAngle(this.toplegleft, -0.22671828F, -0.0F, 0.0F);
      this.neck1 = new MowzieModelRenderer(this, 0, 183);
      this.neck1.setRotationPoint(0.0F, -3.0F, -20.0F);
      this.neck1.addBox(-7.0F, 0.0F, -14.0F, 14, 16, 14, 0.0F);
      this.setRotateAngle(this.neck1, 0.13091688F, -0.0F, 0.0F);
      this.rightbackfoot = new MowzieModelRenderer(this, 230, 70);
      this.rightbackfoot.mirror = true;
      this.rightbackfoot.setRotationPoint(0.0F, 18.92F, 6.99F);
      this.rightbackfoot.addBox(-3.0F, 0.0F, -7.0F, 7, 8, 7, 0.0F);
      this.setRotateAngle(this.rightbackfoot, -0.17627825F, 0.0F, 0.0F);
      this.snout = new MowzieModelRenderer(this, 0, 61);
      this.snout.setRotationPoint(0.0F, 1.5F, -3.9F);
      this.snout.addBox(-2.0F, -3.9F, -5.0F, 5, 4, 6, 1.0F);
      this.setRotateAngle(this.snout, 0.111352004F, -0.0F, 0.0F);
      this.tail5 = new MowzieModelRenderer(this, 94, 243);
      this.tail5.setRotationPoint(0.0F, 1.1156839F, 15.387178F);
      this.tail5.addBox(-3.0F, 0.0F, 0.0F, 6, 7, 20, 0.0F);
      this.setRotateAngle(this.tail5, 0.028972466F, 0.0F, 0.0F);
      this.neck2 = new MowzieModelRenderer(this, 0, 146);
      this.neck2.setRotationPoint(0.0F, 2.9F, -6.7F);
      this.neck2.addBox(-6.0F, 0.0F, -21.0F, 12, 12, 17, 0.0F);
      this.setRotateAngle(this.neck2, -0.30403635F, -0.0F, 0.0F);
      this.bottomlegright = new MowzieModelRenderer(this, 230, 40);
      this.bottomlegright.mirror = true;
      this.bottomlegright.setRotationPoint(0.0F, 17.951286F, 0.036030103F);
      this.bottomlegright.addBox(-3.0F, 0.0F, 0.0F, 7, 19, 7, 0.0F);
      this.setRotateAngle(this.bottomlegright, 0.4029965F, 0.0F, 0.0F);
      this.bottomfrontrightleg = new MowzieModelRenderer(this, 200, 30);
      this.bottomfrontrightleg.mirror = true;
      this.bottomfrontrightleg.setRotationPoint(1.9F, 11.97559F, -0.91391456F);
      this.bottomfrontrightleg.addBox(-2.5F, 0.0F, -3.0F, 6, 13, 6, 0.0F);
      this.setRotateAngle(this.bottomfrontrightleg, -0.31817353F, 0.0F, 0.0F);
      this.frontrighttopleg = new MowzieModelRenderer(this, 200, 0);
      this.frontrighttopleg.mirror = true;
      this.frontrighttopleg.setRotationPoint(-10.9F, 8.917391F, -17.014116F);
      this.frontrighttopleg.addBox(-1.0F, 0.0F, -5.0F, 7, 14, 7, 0.0F);
      this.setRotateAngle(this.frontrighttopleg, -0.07417649F, 0.0F, 0.0F);
      this.neck3 = new MowzieModelRenderer(this, 0, 115);
      this.neck3.setRotationPoint(0.0F, 3.8F, -12.6F);
      this.neck3.addBox(-4.0F, 0.0F, -21.0F, 8, 9, 16, 0.0F);
      this.setRotateAngle(this.neck3, -0.3052581F, -0.0F, 0.0F);
      this.tail3 = new MowzieModelRenderer(this, 94, 167);
      this.tail3.setRotationPoint(0.0F, 0.69239783F, 10.830078F);
      this.tail3.addBox(-4.0F, 0.0F, 0.0F, 8, 13, 15, 0.0F);
      this.setRotateAngle(this.tail3, -0.028274333F, 0.0F, 0.0F);
      this.Stomach = new MowzieModelRenderer(this, 161, 79);
      this.Stomach.setRotationPoint(-1.0F, 1.3F, -4.1F);
      this.Stomach.addBox(-11.0F, -3.0F, -8.0F, 24, 23, 20, 1.0F);
      this.setRotateAngle(this.Stomach, -0.14713125F, -0.0F, 0.0F);
      this.hips = new MowzieModelRenderer(this, 94, 51);
      this.hips.setRotationPoint(0.0F, -0.5F, 11.8F);
      this.hips.addBox(-11.0F, -1.9F, -8.0F, 22, 24, 20, 1.0F);
      this.setRotateAngle(this.hips, -0.24312437F, 0.0F, 0.0F);
      this.tail2 = new MowzieModelRenderer(this, 94, 132);
      this.tail2.setRotationPoint(0.0F, 0.92843664F, 11.97155F);
      this.tail2.addBox(-6.0F, 0.0F, 0.0F, 12, 15, 12, 0.0F);
      this.setRotateAngle(this.tail2, -0.07644542F, 0.0F, 0.0F);
      this.frontrightfoot = new MowzieModelRenderer(this, 200, 50);
      this.frontrightfoot.mirror = true;
      this.frontrightfoot.setRotationPoint(0.0F, 12.854573F, -3.001658F);
      this.frontrightfoot.addBox(-2.5F, 0.0F, 0.0F, 6, 6, 6, 0.0F);
      this.setRotateAngle(this.frontrightfoot, 0.2003638F, 0.0F, 0.0F);
      this.body = new MowzieModelRenderer(this, 94, 0);
      this.body.setRotationPoint(0.0F, -18.0F, 0.0F);
      this.body.addBox(-9.0F, -3.9F, -23.5F, 18, 23, 28, 0.0F);
      this.setRotateAngle(this.body, 0.19198622F, -0.0F, 0.0F);
      this.neck4 = new MowzieModelRenderer(this, 0, 86);
      this.neck4.setRotationPoint(0.0F, 4.1F, -12.3F);
      this.neck4.addBox(-3.0F, 0.0F, -21.0F, 6, 7, 14, 0.0F);
      this.setRotateAngle(this.neck4, -0.36599556F, -0.0F, 0.0F);
      this.head = new MowzieModelRenderer(this, 0, 43);
      this.head.setRotationPoint(-0.5F, 4.4F, -21.4F);
      this.head.addBox(-3.0F, -2.8F, -4.0F, 7, 6, 8, 1.0F);
      this.setRotateAngle(this.head, 0.922232F, -0.0F, 0.0F);
      this.neck5.addChild(this.neck6);
      this.tail5.addChild(this.tail6);
      this.toplegleft.addChild(this.bottomlegleft);
      this.bottomlegleft.addChild(this.leftbackfoot);
      this.hips.addChild(this.tail1);
      this.bottomfrontleftleg.addChild(this.frontleftfoot);
      this.neck4.addChild(this.neck5);
      this.tail3.addChild(this.tail4);
      this.body.addChild(this.frontlefttopleg);
      this.head.addChild(this.jaw);
      this.frontlefttopleg.addChild(this.bottomfrontleftleg);
      this.body.addChild(this.neck1);
      this.bottomlegright.addChild(this.rightbackfoot);
      this.head.addChild(this.snout);
      this.tail4.addChild(this.tail5);
      this.neck1.addChild(this.neck2);
      this.toplegright.addChild(this.bottomlegright);
      this.frontrighttopleg.addChild(this.bottomfrontrightleg);
      this.body.addChild(this.frontrighttopleg);
      this.neck2.addChild(this.neck3);
      this.tail2.addChild(this.tail3);
      this.body.addChild(this.Stomach);
      this.body.addChild(this.hips);
      this.tail1.addChild(this.tail2);
      this.bottomfrontrightleg.addChild(this.frontrightfoot);
      this.neck3.addChild(this.neck4);
      this.neck6.addChild(this.head);
      this.neckParts = new MowzieModelRenderer[]{this.head, this.neck6, this.neck5, this.neck4, this.neck3, this.neck2, this.neck1, this.body};
      this.tailParts = new MowzieModelRenderer[]{this.tail5, this.tail4, this.tail3, this.tail2, this.tail1};
      this.body.updateDefaultPose();
      this.toplegleft.updateDefaultPose();
      this.toplegright.updateDefaultPose();
      this.neck1.updateDefaultPose();
      this.Stomach.updateDefaultPose();
      this.hips.updateDefaultPose();
      this.frontlefttopleg.updateDefaultPose();
      this.frontrighttopleg.updateDefaultPose();
      this.neck2.updateDefaultPose();
      this.neck3.updateDefaultPose();
      this.neck4.updateDefaultPose();
      this.neck5.updateDefaultPose();
      this.neck6.updateDefaultPose();
      this.head.updateDefaultPose();
      this.snout.updateDefaultPose();
      this.jaw.updateDefaultPose();
      this.tail1.updateDefaultPose();
      this.tail2.updateDefaultPose();
      this.tail3.updateDefaultPose();
      this.tail4.updateDefaultPose();
      this.tail5.updateDefaultPose();
      this.tail6.updateDefaultPose();
      this.bottomfrontleftleg.updateDefaultPose();
      this.frontleftfoot.updateDefaultPose();
      this.bottomfrontrightleg.updateDefaultPose();
      this.frontrightfoot.updateDefaultPose();
      this.bottomlegleft.updateDefaultPose();
      this.leftbackfoot.updateDefaultPose();
      this.bottomlegright.updateDefaultPose();
      this.rightbackfoot.updateDefaultPose();
   }

   public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
      super.render(entity, f, f1, f2, f3, f4, f5);
      this.animate((EntityApatosaurus)entity, f, f1, f2, f3, f4, f5);
      this.body.render(f5);
      this.toplegleft.render(f5);
      this.toplegright.render(f5);
   }

   public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, EntityApatosaurus entity) {
      super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
      this.resetPose();
      float globalSpeed = 0.5F;
      float globalHeight = 0.5F;
      float globalDegree = 0.5F;
      float frontOffset = 1.0F;
      MowzieModelRenderer head = this.head;
      MowzieModelRenderer waist = this.hips;
      MowzieModelRenderer thighLeft = this.toplegleft;
      MowzieModelRenderer thighRight = this.toplegright;
      MowzieModelRenderer lowerThighLeft = this.bottomlegleft;
      MowzieModelRenderer lowerThighRight = this.bottomlegright;
      MowzieModelRenderer footLeft = this.leftbackfoot;
      MowzieModelRenderer footRight = this.rightbackfoot;
      MowzieModelRenderer armRight = this.frontrighttopleg;
      MowzieModelRenderer armLeft = this.frontlefttopleg;
      MowzieModelRenderer lowerArmRight = this.bottomfrontrightleg;
      MowzieModelRenderer lowerArmLeft = this.bottomfrontleftleg;
      MowzieModelRenderer handRight = this.frontrightfoot;
      MowzieModelRenderer handLeft = this.frontleftfoot;
      this.bob(this.body, globalSpeed * 1.0F, globalHeight * 4.0F, false, f, f1);
      this.bob(thighLeft, globalSpeed * 1.0F, globalHeight * 1.0F, false, f, f1);
      this.bob(thighRight, globalSpeed * 1.0F, globalHeight * 1.0F, false, f, f1);
      this.chainWave(this.tailParts, globalSpeed * 1.0F, globalHeight * 0.25F, 3.0D, f, f1);
      this.chainSwing(this.tailParts, globalSpeed * 0.5F, globalHeight * 0.5F, 3.0D, f, f1);
      this.chainWave(this.neckParts, globalSpeed * 1.0F, globalHeight * 0.125F, -4.0D, f, f1);
      this.walk(thighLeft, 1.0F * globalSpeed, 0.7F * globalDegree, false, 0.0F, -0.4F, f, f1);
      this.walk(lowerThighLeft, 1.0F * globalSpeed, 0.6F * globalDegree, true, 1.0F, 0.5F, f, f1);
      this.walk(footLeft, 1.0F * globalSpeed, 0.6F * globalDegree, false, -1.5F, 0.85F, f, f1);
      this.walk(thighRight, 1.0F * globalSpeed, 0.7F * globalDegree, true, 0.0F, -0.4F, f, f1);
      this.walk(lowerThighRight, 1.0F * globalSpeed, 0.6F * globalDegree, false, 1.0F, 0.5F, f, f1);
      this.walk(footRight, 1.0F * globalSpeed, 0.6F * globalDegree, true, -1.5F, 0.85F, f, f1);
      this.walk(armLeft, 1.0F * globalSpeed, 0.7F * globalDegree, true, frontOffset + 0.0F, -0.2F, f, f1);
      this.walk(lowerArmLeft, 1.0F * globalSpeed, 0.6F * globalDegree, true, frontOffset + 1.0F, -0.2F, f, f1);
      this.walk(handLeft, 1.0F * globalSpeed, 0.6F * globalDegree, false, frontOffset + 2.0F, 0.8F, f, f1);
      this.walk(armRight, 1.0F * globalSpeed, 0.7F * globalDegree, false, frontOffset + 0.0F, -0.2F, f, f1);
      this.walk(lowerArmRight, 1.0F * globalSpeed, 0.6F * globalDegree, false, frontOffset + 1.0F, -0.2F, f, f1);
      this.walk(handRight, 1.0F * globalSpeed, 0.6F * globalDegree, true, frontOffset + 2.0F, 0.8F, f, f1);
      int ticksExisted = entity.tickCount;
      this.chainWave(this.tailParts, globalSpeed * 0.25F, globalHeight * 2.0F, 3.0D, (float)ticksExisted, 0.1F);
      this.chainSwing(this.tailParts, globalSpeed * 0.125F, globalHeight * 2.0F, 3.0D, (float)ticksExisted, 0.1F);
      this.chainWave(this.neckParts, globalSpeed * 0.25F, globalHeight * 0.25F, -4.0D, (float)ticksExisted, 0.1F);
      entity.tailBuffer.applyChainSwingBuffer(this.tailParts);
   }

   public void resetPose() {
      this.body.resetToDefaultPose();
      this.toplegleft.resetToDefaultPose();
      this.toplegright.resetToDefaultPose();
      this.neck1.resetToDefaultPose();
      this.Stomach.resetToDefaultPose();
      this.hips.resetToDefaultPose();
      this.frontlefttopleg.resetToDefaultPose();
      this.frontrighttopleg.resetToDefaultPose();
      this.neck2.resetToDefaultPose();
      this.neck3.resetToDefaultPose();
      this.neck4.resetToDefaultPose();
      this.neck5.resetToDefaultPose();
      this.neck6.resetToDefaultPose();
      this.head.resetToDefaultPose();
      this.snout.resetToDefaultPose();
      this.jaw.resetToDefaultPose();
      this.tail1.resetToDefaultPose();
      this.tail2.resetToDefaultPose();
      this.tail3.resetToDefaultPose();
      this.tail4.resetToDefaultPose();
      this.tail5.resetToDefaultPose();
      this.tail6.resetToDefaultPose();
      this.bottomfrontleftleg.resetToDefaultPose();
      this.frontleftfoot.resetToDefaultPose();
      this.bottomfrontrightleg.resetToDefaultPose();
      this.frontrightfoot.resetToDefaultPose();
      this.bottomlegleft.resetToDefaultPose();
      this.leftbackfoot.resetToDefaultPose();
      this.bottomlegright.resetToDefaultPose();
      this.rightbackfoot.resetToDefaultPose();
   }

   public void animate(IAnimatedEntity entity, float f, float f1, float f2, float f3, float f4, float f5) {
      this.animator.update(entity);
      this.setRotationAngles(f, f1, f2, f3, f4, f5, (EntityApatosaurus)entity);
   }

   public void setRotateAngle(MowzieModelRenderer modelRenderer, float x, float y, float z) {
      modelRenderer.rotateAngleX = x;
      modelRenderer.rotateAngleY = y;
      modelRenderer.rotateAngleZ = z;
   }
}
