package net.ilexiconn.jurassicraft.client.model.entity;

import net.ilexiconn.llibrary.client.model.tools.ResettableModelRenderer;
import net.ilexiconn.llibrary.client.model.tools.AdvancedModelBase;
import net.minecraft.world.entity.Entity;
import net.minecraft.util.Mth;

public class ModelMoeritherium extends AdvancedModelBase {

   ResettableModelRenderer snout1;
   ResettableModelRenderer snout2;
   ResettableModelRenderer head1;
   ResettableModelRenderer head2;
   ResettableModelRenderer earleft;
   ResettableModelRenderer earright;
   ResettableModelRenderer mouth1;
   ResettableModelRenderer mouth2;
   ResettableModelRenderer body1;
   ResettableModelRenderer body2;
   ResettableModelRenderer body3;
   ResettableModelRenderer tail1;
   ResettableModelRenderer tail2;
   ResettableModelRenderer backlegleft1;
   ResettableModelRenderer backlegleft2;
   ResettableModelRenderer backlegleft3;
   ResettableModelRenderer backlegleft4;
   ResettableModelRenderer backlegright1;
   ResettableModelRenderer backlegright2;
   ResettableModelRenderer backlegright3;
   ResettableModelRenderer backlegright4;
   ResettableModelRenderer frontlegleft1;
   ResettableModelRenderer frontlegleft2;
   ResettableModelRenderer frontlegleft3;
   ResettableModelRenderer frontlegleft4;
   ResettableModelRenderer frontlegright1;
   ResettableModelRenderer frontlegright2;
   ResettableModelRenderer frontlegright3;
   ResettableModelRenderer frontlegright4;


   public ModelMoeritherium() {
      this.textureWidth = 128;
      this.textureHeight = 64;
      this.snout1 = new ResettableModelRenderer(this, 110, 0);
      this.snout1.addBox(-2.5F, -8.2F, -12.0F, 5, 3, 4);
      this.snout1.setRotationPoint(0.0F, 14.5F, -8.5F);
      this.snout1.setTextureSize(128, 64);
      this.snout1.mirror = true;
      this.setRotation(this.snout1, 0.5235988F, 0.0F, 0.0F);
      this.snout2 = new ResettableModelRenderer(this, 110, 7);
      this.snout2.addBox(-2.0F, -13.0F, -9.4F, 4, 3, 3);
      this.snout2.setRotationPoint(0.0F, 14.5F, -8.5F);
      this.snout2.setTextureSize(128, 64);
      this.snout2.mirror = true;
      this.setRotation(this.snout2, 1.047198F, 0.0F, 0.0F);
      this.mouth2 = new ResettableModelRenderer(this, 110, 13);
      this.mouth2.addBox(-2.0F, 0.2F, -12.2F, 4, 2, 4);
      this.mouth2.setRotationPoint(0.0F, 14.5F, -8.5F);
      this.mouth2.setTextureSize(128, 64);
      this.mouth2.mirror = true;
      this.setRotation(this.mouth2, 0.0F, 0.0F, 0.0F);
      this.head1 = new ResettableModelRenderer(this, 56, 11);
      this.head1.addBox(-4.0F, -5.0F, -4.5F, 8, 7, 4);
      this.head1.setRotationPoint(0.0F, 14.5F, -8.5F);
      this.head1.setTextureSize(128, 64);
      this.head1.mirror = true;
      this.setRotation(this.head1, 0.0F, 0.0F, 0.0F);
      this.head2 = new ResettableModelRenderer(this, 80, 10);
      this.head2.addBox(-4.0F, -6.0F, -10.0F, 8, 4, 7);
      this.head2.setRotationPoint(0.0F, 14.5F, -8.5F);
      this.head2.setTextureSize(128, 64);
      this.head2.mirror = true;
      this.setRotation(this.head2, 0.2617994F, 0.0F, 0.0F);
      this.mouth1 = new ResettableModelRenderer(this, 80, 21);
      this.mouth1.addBox(-3.5F, -1.0F, -9.5F, 7, 3, 5);
      this.mouth1.setRotationPoint(0.0F, 14.5F, -8.5F);
      this.mouth1.setTextureSize(128, 64);
      this.mouth1.mirror = true;
      this.setRotation(this.mouth1, 0.0F, 0.0F, 0.0F);
      this.body1 = new ResettableModelRenderer(this, 0, 0);
      this.body1.addBox(-5.5F, -4.5F, -7.0F, 11, 9, 17);
      this.body1.setRotationPoint(0.0F, 14.0F, 0.0F);
      this.body1.setTextureSize(128, 64);
      this.body1.mirror = true;
      this.setRotation(this.body1, 0.0F, 0.0F, 0.0F);
      this.body2 = new ResettableModelRenderer(this, 56, 0);
      this.body2.addBox(-5.0F, -4.0F, 7.0F, 10, 7, 4);
      this.body2.setRotationPoint(0.0F, 14.0F, 3.0F);
      this.body2.setTextureSize(128, 64);
      this.body2.mirror = true;
      this.setRotation(this.body2, 0.0F, 0.0F, 0.0F);
      this.body3 = new ResettableModelRenderer(this, 84, 0);
      this.body3.addBox(-5.0F, -4.0F, -10.0F, 10, 7, 3);
      this.body3.setRotationPoint(0.0F, 14.0F, 0.0F);
      this.body3.setTextureSize(128, 64);
      this.body3.mirror = true;
      this.setRotation(this.body3, 0.0F, 0.0F, 0.0F);
      this.tail1 = new ResettableModelRenderer(this, 40, 32);
      this.tail1.addBox(-0.5F, -1.0F, -1.0F, 1, 5, 1);
      this.tail1.setRotationPoint(0.0F, 11.0F, 14.0F);
      this.tail1.setTextureSize(128, 64);
      this.tail1.mirror = true;
      this.setRotation(this.tail1, 0.5235988F, 0.0F, 0.0F);
      this.tail2 = new ResettableModelRenderer(this, 44, 32);
      this.tail2.addBox(-0.5F, 3.0F, 1.5F, 1, 5, 1);
      this.tail2.setRotationPoint(0.0F, 11.0F, 14.0F);
      this.tail2.setTextureSize(128, 64);
      this.tail2.mirror = true;
      this.setRotation(this.tail2, -0.1745329F, 0.0F, 0.0F);
      this.backlegleft1 = new ResettableModelRenderer(this, 0, 26);
      this.backlegleft1.addBox(-3.0F, -3.25F, -2.0F, 5, 9, 7);
      this.backlegleft1.setRotationPoint(4.0F, 13.0F, 9.5F);
      this.backlegleft1.setTextureSize(128, 64);
      this.backlegleft1.mirror = true;
      this.setRotation(this.backlegleft1, 0.0F, 0.0F, 0.0F);
      this.backlegleft2 = new ResettableModelRenderer(this, 24, 26);
      this.backlegleft2.addBox(-2.0F, 5.7F, 0.0F, 4, 2, 4);
      this.backlegleft2.setRotationPoint(4.0F, 13.0F, 9.5F);
      this.backlegleft2.setTextureSize(128, 64);
      this.backlegleft2.mirror = true;
      this.setRotation(this.backlegleft2, 0.0F, 0.0F, 0.0F);
      this.backlegleft3 = new ResettableModelRenderer(this, 24, 37);
      this.backlegleft3.addBox(-1.5F, 5.5F, 3.0F, 3, 3, 3);
      this.backlegleft3.setRotationPoint(4.0F, 13.0F, 9.5F);
      this.backlegleft3.setTextureSize(128, 64);
      this.backlegleft3.mirror = true;
      this.setRotation(this.backlegleft3, -0.3490659F, 0.0F, 0.0F);
      this.backlegleft4 = new ResettableModelRenderer(this, 40, 26);
      this.backlegleft4.addBox(-2.0F, 9.0F, -1.2F, 4, 2, 4);
      this.backlegleft4.setRotationPoint(4.0F, 13.0F, 9.5F);
      this.backlegleft4.setTextureSize(128, 64);
      this.backlegleft4.mirror = true;
      this.setRotation(this.backlegleft4, 0.0F, 0.0F, 0.0F);
      this.backlegright1 = new ResettableModelRenderer(this, 0, 26);
      this.backlegright1.addBox(-2.0F, -3.25F, -2.0F, 5, 9, 7);
      this.backlegright1.setRotationPoint(-4.0F, 13.0F, 9.5F);
      this.backlegright1.setTextureSize(128, 64);
      this.backlegright1.mirror = true;
      this.setRotation(this.backlegright1, 0.0F, 0.0F, 0.0F);
      this.backlegright2 = new ResettableModelRenderer(this, 24, 26);
      this.backlegright2.addBox(-2.0F, 5.7F, 0.0F, 4, 2, 4);
      this.backlegright2.setRotationPoint(-4.0F, 13.0F, 9.5F);
      this.backlegright2.setTextureSize(128, 64);
      this.backlegright2.mirror = true;
      this.setRotation(this.backlegright2, 0.0F, 0.0F, 0.0F);
      this.backlegright3 = new ResettableModelRenderer(this, 24, 37);
      this.backlegright3.addBox(-1.5F, 5.8F, 2.0F, 3, 3, 3);
      this.backlegright3.setRotationPoint(-4.0F, 13.0F, 10.5F);
      this.backlegright3.setTextureSize(128, 64);
      this.backlegright3.mirror = true;
      this.setRotation(this.backlegright3, -0.3490659F, 0.0F, 0.0F);
      this.backlegright4 = new ResettableModelRenderer(this, 40, 26);
      this.backlegright4.addBox(-2.0F, 9.0F, -1.2F, 4, 2, 4);
      this.backlegright4.setRotationPoint(-4.0F, 13.0F, 9.5F);
      this.backlegright4.setTextureSize(128, 64);
      this.backlegright4.mirror = true;
      this.setRotation(this.backlegright4, 0.0F, 0.0F, 0.0F);
      this.frontlegleft1 = new ResettableModelRenderer(this, 0, 26);
      this.frontlegleft1.addBox(-3.0F, -2.0F, -3.0F, 5, 9, 7);
      this.frontlegleft1.setRotationPoint(4.0F, 13.0F, -5.5F);
      this.frontlegleft1.setTextureSize(128, 64);
      this.frontlegleft1.mirror = true;
      this.setRotation(this.frontlegleft1, 0.0F, 0.0F, 0.0F);
      this.frontlegleft2 = new ResettableModelRenderer(this, 24, 32);
      this.frontlegleft2.addBox(-2.5F, 7.0F, -0.5F, 4, 1, 4);
      this.frontlegleft2.setRotationPoint(4.0F, 13.0F, -5.5F);
      this.frontlegleft2.setTextureSize(128, 64);
      this.frontlegleft2.mirror = true;
      this.setRotation(this.frontlegleft2, 0.0F, 0.0F, 0.0F);
      this.frontlegleft3 = new ResettableModelRenderer(this, 24, 37);
      this.frontlegleft3.addBox(-2.0F, 6.2F, 2.8F, 3, 3, 3);
      this.frontlegleft3.setRotationPoint(4.0F, 13.0F, -5.5F);
      this.frontlegleft3.setTextureSize(128, 64);
      this.frontlegleft3.mirror = true;
      this.setRotation(this.frontlegleft3, -0.3490659F, 0.0F, 0.0F);
      this.frontlegleft4 = new ResettableModelRenderer(this, 40, 26);
      this.frontlegleft4.addBox(-2.5F, 9.0F, -1.2F, 4, 2, 4);
      this.frontlegleft4.setRotationPoint(4.0F, 13.0F, -5.5F);
      this.frontlegleft4.setTextureSize(128, 64);
      this.frontlegleft4.mirror = true;
      this.setRotation(this.frontlegleft4, 0.0F, 0.0F, 0.0F);
      this.frontlegright1 = new ResettableModelRenderer(this, 0, 26);
      this.frontlegright1.addBox(-2.0F, -2.0F, -3.0F, 5, 9, 7);
      this.frontlegright1.setRotationPoint(-4.0F, 13.0F, -5.5F);
      this.frontlegright1.setTextureSize(128, 64);
      this.frontlegright1.mirror = true;
      this.setRotation(this.frontlegright1, 0.0F, 0.0F, 0.0F);
      this.frontlegright2 = new ResettableModelRenderer(this, 24, 32);
      this.frontlegright2.addBox(-1.5F, 7.0F, -0.5F, 4, 1, 4);
      this.frontlegright2.setRotationPoint(-4.0F, 13.0F, -5.5F);
      this.frontlegright2.setTextureSize(128, 64);
      this.frontlegright2.mirror = true;
      this.setRotation(this.frontlegright2, 0.0F, 0.0F, 0.0F);
      this.frontlegright3 = new ResettableModelRenderer(this, 24, 37);
      this.frontlegright3.addBox(-1.0F, 6.2F, 2.8F, 3, 3, 3);
      this.frontlegright3.setRotationPoint(-4.0F, 13.0F, -5.5F);
      this.frontlegright3.setTextureSize(128, 64);
      this.frontlegright3.mirror = true;
      this.setRotation(this.frontlegright3, -0.3490659F, 0.0F, 0.0F);
      this.frontlegright4 = new ResettableModelRenderer(this, 40, 26);
      this.frontlegright4.addBox(-1.5F, 9.0F, -1.2F, 4, 2, 4);
      this.frontlegright4.setRotationPoint(-4.0F, 13.0F, -5.5F);
      this.frontlegright4.setTextureSize(128, 64);
      this.frontlegright4.mirror = true;
      this.setRotation(this.frontlegright4, 0.0F, 0.0F, 0.0F);
      this.earleft = new ResettableModelRenderer(this, 114, 19);
      this.earleft.addBox(1.5F, -1.5F, -5.0F, 2, 3, 0);
      this.earleft.setRotationPoint(0.0F, 14.5F, -10.0F);
      this.earleft.setTextureSize(128, 64);
      this.earleft.mirror = true;
      this.setRotation(this.earleft, -0.2617994F, -0.6981317F, -0.5235988F);
      this.earright = new ResettableModelRenderer(this, 110, 19);
      this.earright.addBox(-3.5F, -1.5F, -5.0F, 2, 3, 0);
      this.earright.setRotationPoint(0.0F, 14.5F, -10.0F);
      this.earright.setTextureSize(128, 64);
      this.earright.mirror = true;
      this.setRotation(this.earright, -0.2617994F, 0.6981317F, 0.5235988F);
      this.snout1.savefirstParameters();
      this.snout2.savefirstParameters();
      this.mouth2.savefirstParameters();
      this.head1.savefirstParameters();
      this.head2.savefirstParameters();
      this.mouth1.savefirstParameters();
      this.body1.savefirstParameters();
      this.body2.savefirstParameters();
      this.body3.savefirstParameters();
      this.tail1.savefirstParameters();
      this.tail2.savefirstParameters();
      this.backlegleft1.savefirstParameters();
      this.backlegleft2.savefirstParameters();
      this.backlegleft3.savefirstParameters();
      this.backlegleft4.savefirstParameters();
      this.backlegright1.savefirstParameters();
      this.backlegright2.savefirstParameters();
      this.backlegright3.savefirstParameters();
      this.backlegright4.savefirstParameters();
      this.frontlegleft1.savefirstParameters();
      this.frontlegleft2.savefirstParameters();
      this.frontlegleft3.savefirstParameters();
      this.frontlegleft4.savefirstParameters();
      this.frontlegright1.savefirstParameters();
      this.frontlegright2.savefirstParameters();
      this.frontlegright3.savefirstParameters();
      this.frontlegright4.savefirstParameters();
      this.earleft.savefirstParameters();
      this.earright.savefirstParameters();
   }

   public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
      super.render(entity, f, f1, f2, f3, f4, f5);
      this.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
      this.snout1.render(f5);
      this.snout2.render(f5);
      this.mouth2.render(f5);
      this.head1.render(f5);
      this.head2.render(f5);
      this.mouth1.render(f5);
      this.body1.render(f5);
      this.body2.render(f5);
      this.body3.render(f5);
      this.tail1.render(f5);
      this.tail2.render(f5);
      this.backlegleft1.render(f5);
      this.backlegleft2.render(f5);
      this.backlegleft3.render(f5);
      this.backlegleft4.render(f5);
      this.backlegright1.render(f5);
      this.backlegright2.render(f5);
      this.backlegright3.render(f5);
      this.backlegright4.render(f5);
      this.frontlegleft1.render(f5);
      this.frontlegleft2.render(f5);
      this.frontlegleft3.render(f5);
      this.frontlegleft4.render(f5);
      this.frontlegright1.render(f5);
      this.frontlegright2.render(f5);
      this.frontlegright3.render(f5);
      this.frontlegright4.render(f5);
      this.earleft.render(f5);
      this.earright.render(f5);
   }

   private void setRotation(ResettableModelRenderer model, float x, float y, float z) {
      model.rotateAngleX = x;
      model.rotateAngleY = y;
      model.rotateAngleZ = z;
   }

   public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
      super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
      float headMovementX = f4 / 57.295776F;
      float headMovementY = f3 / 57.295776F;
      float snoutNaturalMovement = Mth.cos(0.1F * f2);
      float legMovement1 = Mth.cos(f * 0.6662F + 3.1415927F) * 1.4F * f1;
      float legMovement2 = Mth.cos(f * 0.6662F) * 1.4F * f1;
      float tailMovement1 = 0.05F * Mth.cos(0.1F * f2);
      float tailMovement2 = 0.05F * Mth.sin(0.1F * f2);
      this.body1.rotateAngleX = this.body1.firstRotateAngleX;
      this.body2.rotateAngleX = this.body1.firstRotateAngleX;
      this.body3.rotateAngleX = this.body1.firstRotateAngleX;
      this.head1.rotateAngleX = headMovementX + this.head1.firstRotateAngleX;
      this.head2.rotateAngleX = headMovementX + this.head2.firstRotateAngleX;
      this.snout1.rotateAngleX = headMovementX + 0.01F * snoutNaturalMovement + this.snout1.firstRotateAngleX;
      this.snout2.rotateAngleX = headMovementX + 0.02F * snoutNaturalMovement + this.snout2.firstRotateAngleX;
      this.mouth1.rotateAngleX = headMovementX + this.mouth1.firstRotateAngleX;
      this.mouth2.rotateAngleX = headMovementX + this.mouth2.firstRotateAngleX;
      this.earright.rotateAngleX = headMovementX + this.earright.firstRotateAngleX;
      this.earleft.rotateAngleX = headMovementX + this.earleft.firstRotateAngleX;
      this.head1.rotateAngleY = headMovementY + this.head1.firstRotateAngleY;
      this.head2.rotateAngleY = headMovementY + this.head2.firstRotateAngleY;
      this.snout1.rotateAngleY = headMovementY + this.snout1.firstRotateAngleY;
      this.snout2.rotateAngleY = headMovementY + this.snout2.firstRotateAngleY;
      this.mouth1.rotateAngleY = headMovementY + this.mouth1.firstRotateAngleY;
      this.mouth2.rotateAngleY = headMovementY + this.mouth2.firstRotateAngleY;
      this.earright.rotateAngleY = headMovementY + this.earright.firstRotateAngleY;
      this.earleft.rotateAngleY = headMovementY + this.earleft.firstRotateAngleY;
      this.earright.rotateAngleZ = this.earright.firstRotateAngleZ;
      this.earleft.rotateAngleZ = this.earleft.firstRotateAngleZ;
      this.frontlegleft1.rotateAngleX = legMovement1 + this.frontlegleft1.firstRotateAngleX;
      this.frontlegleft2.rotateAngleX = legMovement1 + this.frontlegleft2.firstRotateAngleX;
      this.frontlegleft3.rotateAngleX = legMovement1 + this.frontlegleft3.firstRotateAngleX;
      this.frontlegleft4.rotateAngleX = legMovement1 + this.frontlegleft4.firstRotateAngleX;
      this.backlegright1.rotateAngleX = legMovement1 + this.backlegright1.firstRotateAngleX;
      this.backlegright2.rotateAngleX = legMovement1 + this.backlegright2.firstRotateAngleX;
      this.backlegright3.rotateAngleX = legMovement1 + this.backlegright3.firstRotateAngleX;
      this.backlegright4.rotateAngleX = legMovement1 + this.backlegright4.firstRotateAngleX;
      this.frontlegright1.rotateAngleX = legMovement2 + this.frontlegright1.firstRotateAngleX;
      this.frontlegright2.rotateAngleX = legMovement2 + this.frontlegright2.firstRotateAngleX;
      this.frontlegright3.rotateAngleX = legMovement2 + this.frontlegright3.firstRotateAngleX;
      this.frontlegright4.rotateAngleX = legMovement2 + this.frontlegright4.firstRotateAngleX;
      this.backlegleft1.rotateAngleX = legMovement2 + this.backlegleft1.firstRotateAngleX;
      this.backlegleft2.rotateAngleX = legMovement2 + this.backlegleft2.firstRotateAngleX;
      this.backlegleft3.rotateAngleX = legMovement2 + this.backlegleft3.firstRotateAngleX;
      this.backlegleft4.rotateAngleX = legMovement2 + this.backlegleft4.firstRotateAngleX;
      this.tail1.rotateAngleZ = tailMovement1 + this.tail1.firstRotateAngleZ;
      this.tail2.rotateAngleZ = tailMovement1 + this.tail2.firstRotateAngleZ;
      this.tail1.rotateAngleY = tailMovement2 + this.tail1.firstRotateAngleY;
      this.tail2.rotateAngleY = tailMovement2 + this.tail2.firstRotateAngleY;
      this.tail1.rotateAngleX = tailMovement2 + this.tail1.firstRotateAngleX;
      this.tail2.rotateAngleX = tailMovement2 + this.tail2.firstRotateAngleX;
   }
}
