package net.ilexiconn.jurassicraft.client.model.entity;

import net.ilexiconn.jurassicraft.client.model.animation.Animator;
import net.ilexiconn.jurassicraft.client.model.base.MowzieModelBase;
import net.ilexiconn.jurassicraft.client.model.base.MowzieModelRenderer;
import net.ilexiconn.jurassicraft.common.api.IAnimatedEntity;
import net.ilexiconn.jurassicraft.common.entity.dinosaurs.EntityMamenchisaurus;
import net.minecraft.world.entity.Entity;
import net.minecraftforge.api.distmarker.Dist;
import net.minecraftforge.api.distmarker.OnlyIn;

@OnlyIn(Dist.CLIENT)
public class ModelMamenchisaurus extends MowzieModelBase {

   public Animator animator = new Animator(this);
   MowzieModelRenderer hips;
   MowzieModelRenderer toplegleft;
   MowzieModelRenderer toplegright;
   MowzieModelRenderer tail1;
   MowzieModelRenderer body;
   MowzieModelRenderer tail2;
   MowzieModelRenderer tail3;
   MowzieModelRenderer tail4;
   MowzieModelRenderer tail5;
   MowzieModelRenderer tail6;
   MowzieModelRenderer tail7;
   MowzieModelRenderer tail8;
   MowzieModelRenderer tail9;
   MowzieModelRenderer tail10;
   MowzieModelRenderer neck1;
   MowzieModelRenderer Stomach;
   MowzieModelRenderer frontlefttopleg;
   MowzieModelRenderer frontrighttopleg;
   MowzieModelRenderer neck2;
   MowzieModelRenderer neck3;
   MowzieModelRenderer neck4;
   MowzieModelRenderer neck5;
   MowzieModelRenderer neck6;
   MowzieModelRenderer neck7;
   MowzieModelRenderer neck8;
   MowzieModelRenderer neck9;
   MowzieModelRenderer neck10;
   MowzieModelRenderer neck11;
   MowzieModelRenderer Head;
   MowzieModelRenderer UpperJaw;
   MowzieModelRenderer LowerJaw;
   MowzieModelRenderer HeadSlope;
   MowzieModelRenderer bottomfrontleftleg;
   MowzieModelRenderer frontleftfoot;
   MowzieModelRenderer bottomfrontrightleg;
   MowzieModelRenderer frontrightfoot;
   MowzieModelRenderer bottomlegleft;
   MowzieModelRenderer leftbackfoot;
   MowzieModelRenderer bottomlegright;
   MowzieModelRenderer rightbackfoot;
   MowzieModelRenderer[] neckParts;
   MowzieModelRenderer[] tailParts;


   public ModelMamenchisaurus() {
      this.textureWidth = 512;
      this.textureHeight = 512;
      this.tail2 = new MowzieModelRenderer(this, 94, 132);
      this.tail2.setRotationPoint(0.0F, 0.4F, 13.8F);
      this.tail2.addBox(-8.0F, 0.0F, 0.0F, 16, 17, 13, 0.0F);
      this.setRotateAngle(this.tail2, -0.045553092F, -0.0F, 0.0F);
      this.tail8 = new MowzieModelRenderer(this, 19, 243);
      this.tail8.setRotationPoint(0.0F, 0.6F, 24.1F);
      this.tail8.addBox(-2.5F, 0.0F, 0.0F, 5, 5, 25, 0.0F);
      this.setRotateAngle(this.tail8, 0.091106184F, -0.0F, 0.0F);
      this.bottomlegright = new MowzieModelRenderer(this, 232, 40);
      this.bottomlegright.setRotationPoint(-5.0F, 18.2F, -5.3F);
      this.bottomlegright.addBox(-3.5F, 0.0F, 0.0F, 8, 19, 9, 0.0F);
      this.setRotateAngle(this.bottomlegright, 0.4029965F, 0.0F, 0.0F);
      this.toplegright = new MowzieModelRenderer(this, 232, 0);
      this.toplegright.setRotationPoint(-7.5F, -17.56F, 22.45F);
      this.toplegright.addBox(-9.0F, -2.96F, -5.8F, 9, 22, 12, 0.0F);
      this.setRotateAngle(this.toplegright, -0.23177972F, 0.0F, 0.0F);
      this.frontrighttopleg = new MowzieModelRenderer(this, 194, 0);
      this.frontrighttopleg.setRotationPoint(-9.9F, 9.6F, -19.2F);
      this.frontrighttopleg.addBox(-5.0F, -3.71F, -2.63F, 8, 17, 10, 0.0F);
      this.setRotateAngle(this.frontrighttopleg, -0.091106184F, 0.0F, 0.0F);
      this.frontleftfoot = new MowzieModelRenderer(this, 200, 55);
      this.frontleftfoot.setRotationPoint(0.0F, 17.0F, -3.0F);
      this.frontleftfoot.addBox(-3.5F, 0.0F, 0.0F, 7, 6, 8, 0.0F);
      this.setRotateAngle(this.frontleftfoot, 0.2178171F, 0.0F, 0.0F);
      this.frontlefttopleg = new MowzieModelRenderer(this, 194, 0);
      this.frontlefttopleg.setRotationPoint(9.9F, 9.6F, -19.2F);
      this.frontlefttopleg.addBox(-3.0F, -3.71F, -2.63F, 8, 17, 10, 0.0F);
      this.setRotateAngle(this.frontlefttopleg, -0.091106184F, 0.0F, 0.0F);
      this.neck3 = new MowzieModelRenderer(this, 0, 119);
      this.neck3.setRotationPoint(0.0F, 1.7F, -17.8F);
      this.neck3.addBox(-6.0F, 0.0F, -22.0F, 12, 13, 22, 0.0F);
      this.setRotateAngle(this.neck3, -0.22759093F, -0.0F, 0.0F);
      this.neck7 = new MowzieModelRenderer(this, 137, 60);
      this.neck7.setRotationPoint(0.0F, 0.1F, -21.08F);
      this.neck7.addBox(-2.5F, 0.0F, -22.0F, 5, 7, 22, 0.0F);
      this.setRotateAngle(this.neck7, 0.18587756F, -0.0F, 0.0F);
      this.tail6 = new MowzieModelRenderer(this, 94, 275);
      this.tail6.setRotationPoint(0.0F, 0.4F, 18.6F);
      this.tail6.addBox(-3.5F, 0.0F, 0.0F, 7, 9, 22, 0.0F);
      this.setRotateAngle(this.tail6, 0.045553092F, -0.0F, 0.0F);
      this.Stomach = new MowzieModelRenderer(this, 177, 91);
      this.Stomach.setRotationPoint(-1.0F, 0.8F, -3.3F);
      this.Stomach.addBox(-10.0F, -2.0F, -8.0F, 22, 23, 24, 0.0F);
      this.setRotateAngle(this.Stomach, -0.091106184F, -0.0F, 0.0F);
      this.bottomfrontrightleg = new MowzieModelRenderer(this, 200, 30);
      this.bottomfrontrightleg.setRotationPoint(-1.0F, 10.43F, 2.25F);
      this.bottomfrontrightleg.addBox(-3.5F, 0.0F, -3.0F, 7, 17, 8, 0.0F);
      this.setRotateAngle(this.bottomfrontrightleg, -0.3530801F, 0.0F, 0.0F);
      this.tail7 = new MowzieModelRenderer(this, 94, 316);
      this.tail7.setRotationPoint(0.0F, 0.7F, 21.0F);
      this.tail7.addBox(-3.0F, 0.0F, 0.0F, 6, 7, 25, 0.0F);
      this.setRotateAngle(this.tail7, 0.045553092F, -0.0F, 0.0F);
      this.neck11 = new MowzieModelRenderer(this, 35, 51);
      this.neck11.setRotationPoint(0.0F, 0.0F, -4.0F);
      this.neck11.addBox(-2.0F, 0.0F, -4.0F, 4, 6, 4, 0.0F);
      this.setRotateAngle(this.neck11, 0.13962634F, 0.0F, 0.0F);
      this.neck8 = new MowzieModelRenderer(this, 53, 61);
      this.neck8.setRotationPoint(0.0F, 0.33F, -21.84F);
      this.neck8.addBox(-2.0F, 0.0F, -6.0F, 4, 6, 6, 0.0F);
      this.setRotateAngle(this.neck8, 0.11606439F, 0.0F, 0.0F);
      this.bottomfrontleftleg = new MowzieModelRenderer(this, 200, 30);
      this.bottomfrontleftleg.setRotationPoint(1.0F, 10.43F, 2.25F);
      this.bottomfrontleftleg.addBox(-3.5F, 0.0F, -3.0F, 7, 17, 8, 0.0F);
      this.setRotateAngle(this.bottomfrontleftleg, -0.3530801F, 0.0F, 0.0F);
      this.tail5 = new MowzieModelRenderer(this, 94, 243);
      this.tail5.setRotationPoint(0.0F, 0.4F, 13.9F);
      this.tail5.addBox(-4.5F, 0.0F, 0.0F, 9, 11, 20, 0.0F);
      this.HeadSlope = new MowzieModelRenderer(this, 23, 20);
      this.HeadSlope.setRotationPoint(0.0F, -1.0F, -6.0F);
      this.HeadSlope.addBox(-1.5F, 0.0F, 0.0F, 3, 2, 6, 0.0F);
      this.setRotateAngle(this.HeadSlope, 0.3307399F, 0.0F, 0.0F);
      this.hips = new MowzieModelRenderer(this, 177, 147);
      this.hips.setRotationPoint(0.0F, -17.56F, 22.45F);
      this.hips.addBox(-10.5F, -10.46F, -16.65F, 21, 24, 23, 0.0F);
      this.tail4 = new MowzieModelRenderer(this, 94, 213);
      this.tail4.setRotationPoint(0.0F, 0.4F, 14.0F);
      this.tail4.addBox(-5.5F, 0.0F, 0.0F, 11, 13, 17, 0.0F);
      this.rightbackfoot = new MowzieModelRenderer(this, 232, 70);
      this.rightbackfoot.setRotationPoint(0.0F, 18.6F, 7.0F);
      this.rightbackfoot.addBox(-3.5F, 0.0F, -7.0F, 8, 8, 9, 0.0F);
      this.setRotateAngle(this.rightbackfoot, -0.17627825F, 0.0F, 0.0F);
      this.tail1 = new MowzieModelRenderer(this, 94, 95);
      this.tail1.setRotationPoint(0.0F, -10.16F, 6.05F);
      this.tail1.addBox(-9.5F, 0.0F, 0.0F, 19, 19, 14, 0.0F);
      this.setRotateAngle(this.tail1, -0.091106184F, -0.0F, 0.0F);
      this.LowerJaw = new MowzieModelRenderer(this, 0, 34);
      this.LowerJaw.setRotationPoint(0.0F, 5.0F, -4.3F);
      this.LowerJaw.addBox(-1.5F, -1.0F, -7.0F, 3, 2, 7, 0.0F);
      this.setRotateAngle(this.LowerJaw, -0.14713125F, 0.0F, 0.0F);
      this.neck6 = new MowzieModelRenderer(this, 35, 9);
      this.neck6.setRotationPoint(0.0F, 0.2F, -26.2F);
      this.neck6.addBox(-3.0F, 0.0F, -22.0F, 6, 8, 22, 0.0F);
      this.setRotateAngle(this.neck6, 0.18203785F, -0.0F, 0.0F);
      this.neck9 = new MowzieModelRenderer(this, 35, 51);
      this.neck9.setRotationPoint(0.0F, 0.0F, -6.0F);
      this.neck9.addBox(-2.0F, 0.0F, -4.0F, 4, 6, 4, 0.0F);
      this.setRotateAngle(this.neck9, 0.19198622F, 0.0F, 0.0F);
      this.UpperJaw = new MowzieModelRenderer(this, 0, 20);
      this.UpperJaw.setRotationPoint(0.0F, 3.05F, -5.6F);
      this.UpperJaw.addBox(-2.0F, -1.0F, -6.0F, 4, 2, 6, 0.0F);
      this.neck4 = new MowzieModelRenderer(this, 0, 74);
      this.neck4.setRotationPoint(0.0F, 1.5F, -19.0F);
      this.neck4.addBox(-5.0F, 0.0F, -27.0F, 10, 11, 27, 0.0F);
      this.setRotateAngle(this.neck4, -0.22759093F, -0.0F, 0.0F);
      this.tail10 = new MowzieModelRenderer(this, 51, 275);
      this.tail10.setRotationPoint(0.0F, 0.3F, 29.0F);
      this.tail10.addBox(-1.5F, 0.0F, 0.0F, 3, 3, 35, 0.0F);
      this.setRotateAngle(this.tail10, 0.045553092F, 0.0F, 0.0F);
      this.neck10 = new MowzieModelRenderer(this, 35, 51);
      this.neck10.setRotationPoint(0.0F, -0.03F, -4.0F);
      this.neck10.addBox(-2.0F, 0.0F, -4.0F, 4, 6, 4, 0.0F);
      this.setRotateAngle(this.neck10, 0.15707964F, 0.0F, 0.0F);
      this.bottomlegleft = new MowzieModelRenderer(this, 232, 40);
      this.bottomlegleft.setRotationPoint(4.0F, 18.23F, -5.31F);
      this.bottomlegleft.addBox(-3.5F, 0.0F, 0.0F, 8, 19, 9, 0.0F);
      this.setRotateAngle(this.bottomlegleft, 0.4029965F, 0.0F, 0.0F);
      this.body = new MowzieModelRenderer(this, 94, 0);
      this.body.setRotationPoint(0.0F, -4.11F, -21.71F);
      this.body.addBox(-9.5F, -5.0F, -23.5F, 19, 24, 30, 0.0F);
      this.setRotateAngle(this.body, 0.22567107F, 0.0F, 0.0F);
      this.neck5 = new MowzieModelRenderer(this, 48, 54);
      this.neck5.setRotationPoint(0.0F, 0.9F, -25.0F);
      this.neck5.addBox(-4.0F, 0.0F, -27.0F, 8, 9, 27, 0.0F);
      this.setRotateAngle(this.neck5, -0.091106184F, -0.0F, 0.0F);
      this.toplegleft = new MowzieModelRenderer(this, 232, 0);
      this.toplegleft.setRotationPoint(7.5F, -17.56F, 22.45F);
      this.toplegleft.addBox(0.0F, -2.96F, -5.8F, 9, 22, 12, 0.0F);
      this.setRotateAngle(this.toplegleft, -0.23177972F, 0.0F, 0.0F);
      this.Head = new MowzieModelRenderer(this, 0, 0);
      this.Head.setRotationPoint(0.0F, 0.0F, -3.83F);
      this.Head.addBox(-2.5F, 0.0F, -6.0F, 5, 6, 6, 0.0F);
      this.setRotateAngle(this.Head, 0.12374385F, 0.0F, 0.0F);
      this.tail3 = new MowzieModelRenderer(this, 94, 167);
      this.tail3.setRotationPoint(0.0F, 0.4F, 11.3F);
      this.tail3.addBox(-6.5F, 0.0F, 0.0F, 13, 15, 15, 0.0F);
      this.frontrightfoot = new MowzieModelRenderer(this, 200, 55);
      this.frontrightfoot.setRotationPoint(0.0F, 17.0F, -3.0F);
      this.frontrightfoot.addBox(-3.5F, 0.0F, 0.0F, 7, 6, 8, 0.0F);
      this.setRotateAngle(this.frontrightfoot, 0.2178171F, 0.0F, 0.0F);
      this.leftbackfoot = new MowzieModelRenderer(this, 232, 70);
      this.leftbackfoot.setRotationPoint(0.0F, 18.6F, 7.0F);
      this.leftbackfoot.addBox(-3.5F, 0.0F, -7.0F, 8, 8, 9, 0.0F);
      this.setRotateAngle(this.leftbackfoot, -0.17627825F, 0.0F, 0.0F);
      this.neck1 = new MowzieModelRenderer(this, 0, 202);
      this.neck1.setRotationPoint(0.0F, -1.9F, -17.1F);
      this.neck1.addBox(-8.0F, 0.0F, -20.0F, 16, 18, 21, 0.0F);
      this.setRotateAngle(this.neck1, -0.3642502F, -0.0F, 0.0F);
      this.tail9 = new MowzieModelRenderer(this, 6, 289);
      this.tail9.setRotationPoint(0.0F, 0.5F, 23.4F);
      this.tail9.addBox(-2.0F, 0.0F, 0.0F, 4, 4, 30, 0.0F);
      this.setRotateAngle(this.tail9, 0.045553092F, -0.0F, 0.0F);
      this.neck2 = new MowzieModelRenderer(this, 0, 159);
      this.neck2.setRotationPoint(0.0F, 2.7F, -14.0F);
      this.neck2.addBox(-7.0F, 0.0F, -22.0F, 14, 15, 22, 0.0F);
      this.setRotateAngle(this.neck2, -0.27314404F, -0.0F, 0.0F);
      this.tail1.addChild(this.tail2);
      this.tail7.addChild(this.tail8);
      this.toplegright.addChild(this.bottomlegright);
      this.body.addChild(this.frontrighttopleg);
      this.bottomfrontleftleg.addChild(this.frontleftfoot);
      this.body.addChild(this.frontlefttopleg);
      this.neck2.addChild(this.neck3);
      this.neck6.addChild(this.neck7);
      this.tail5.addChild(this.tail6);
      this.body.addChild(this.Stomach);
      this.frontrighttopleg.addChild(this.bottomfrontrightleg);
      this.tail6.addChild(this.tail7);
      this.neck10.addChild(this.neck11);
      this.neck7.addChild(this.neck8);
      this.frontlefttopleg.addChild(this.bottomfrontleftleg);
      this.tail4.addChild(this.tail5);
      this.UpperJaw.addChild(this.HeadSlope);
      this.tail3.addChild(this.tail4);
      this.bottomlegright.addChild(this.rightbackfoot);
      this.hips.addChild(this.tail1);
      this.Head.addChild(this.LowerJaw);
      this.neck5.addChild(this.neck6);
      this.neck8.addChild(this.neck9);
      this.Head.addChild(this.UpperJaw);
      this.neck3.addChild(this.neck4);
      this.tail9.addChild(this.tail10);
      this.neck9.addChild(this.neck10);
      this.toplegleft.addChild(this.bottomlegleft);
      this.hips.addChild(this.body);
      this.neck4.addChild(this.neck5);
      this.neck11.addChild(this.Head);
      this.tail2.addChild(this.tail3);
      this.bottomfrontrightleg.addChild(this.frontrightfoot);
      this.bottomlegleft.addChild(this.leftbackfoot);
      this.body.addChild(this.neck1);
      this.tail8.addChild(this.tail9);
      this.neck1.addChild(this.neck2);
      this.neckParts = new MowzieModelRenderer[]{this.Head, this.neck11, this.neck10, this.neck9, this.neck8, this.neck7, this.neck6, this.neck5, this.neck4, this.neck3, this.neck2, this.neck1, this.body};
      this.tailParts = new MowzieModelRenderer[]{this.tail10, this.tail9, this.tail8, this.tail7, this.tail6, this.tail5, this.tail4, this.tail3, this.tail2, this.tail1};
      this.hips.updateDefaultPose();
      this.toplegleft.updateDefaultPose();
      this.toplegright.updateDefaultPose();
      this.tail1.updateDefaultPose();
      this.body.updateDefaultPose();
      this.tail2.updateDefaultPose();
      this.tail3.updateDefaultPose();
      this.tail4.updateDefaultPose();
      this.tail5.updateDefaultPose();
      this.tail6.updateDefaultPose();
      this.tail7.updateDefaultPose();
      this.tail8.updateDefaultPose();
      this.tail9.updateDefaultPose();
      this.tail10.updateDefaultPose();
      this.neck1.updateDefaultPose();
      this.Stomach.updateDefaultPose();
      this.frontlefttopleg.updateDefaultPose();
      this.frontrighttopleg.updateDefaultPose();
      this.neck2.updateDefaultPose();
      this.neck3.updateDefaultPose();
      this.neck4.updateDefaultPose();
      this.neck5.updateDefaultPose();
      this.neck6.updateDefaultPose();
      this.neck7.updateDefaultPose();
      this.neck8.updateDefaultPose();
      this.neck9.updateDefaultPose();
      this.neck10.updateDefaultPose();
      this.neck11.updateDefaultPose();
      this.Head.updateDefaultPose();
      this.UpperJaw.updateDefaultPose();
      this.LowerJaw.updateDefaultPose();
      this.HeadSlope.updateDefaultPose();
      this.bottomfrontleftleg.updateDefaultPose();
      this.frontleftfoot.updateDefaultPose();
      this.bottomfrontrightleg.updateDefaultPose();
      this.frontrightfoot.updateDefaultPose();
      this.bottomlegleft.updateDefaultPose();
      this.leftbackfoot.updateDefaultPose();
      this.bottomlegright.updateDefaultPose();
      this.rightbackfoot.updateDefaultPose();
   }

   public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
      super.render(entity, f, f1, f2, f3, f4, f5);
      this.animate((EntityMamenchisaurus)entity, f, f1, f2, f3, f4, f5);
      this.hips.render(f5);
      this.toplegleft.render(f5);
      this.toplegright.render(f5);
   }

   public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, EntityMamenchisaurus entity) {
      super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
      this.resetPose();
      float globalSpeed = 0.5F;
      float globalHeight = 0.5F;
      float globalDegree = 0.5F;
      float frontOffset = 1.0F;
      MowzieModelRenderer thighLeft = this.toplegleft;
      MowzieModelRenderer thighRight = this.toplegright;
      MowzieModelRenderer lowerThighLeft = this.bottomlegleft;
      MowzieModelRenderer lowerThighRight = this.bottomlegright;
      MowzieModelRenderer footLeft = this.leftbackfoot;
      MowzieModelRenderer footRight = this.rightbackfoot;
      MowzieModelRenderer armRight = this.frontrighttopleg;
      MowzieModelRenderer armLeft = this.frontlefttopleg;
      MowzieModelRenderer lowerArmRight = this.bottomfrontrightleg;
      MowzieModelRenderer lowerArmLeft = this.bottomfrontleftleg;
      MowzieModelRenderer handRight = this.frontrightfoot;
      MowzieModelRenderer handLeft = this.frontleftfoot;
      MowzieModelRenderer waist = this.hips;
      this.bob(waist, globalSpeed * 1.0F, globalHeight * 4.0F, false, f, f1);
      this.bob(thighLeft, globalSpeed * 1.0F, globalHeight * 1.0F, false, f, f1);
      this.bob(thighRight, globalSpeed * 1.0F, globalHeight * 1.0F, false, f, f1);
      this.chainWave(this.tailParts, globalSpeed * 1.0F, globalHeight * 0.25F, 3.0D, f, f1);
      this.chainSwing(this.tailParts, globalSpeed * 0.5F, globalHeight * 0.5F, 3.0D, f, f1);
      this.chainWave(this.neckParts, globalSpeed * 1.0F, globalHeight * 0.125F, -4.0D, f, f1);
      this.walk(thighLeft, 1.0F * globalSpeed, 0.7F * globalDegree, false, 0.0F, -0.4F, f, f1);
      this.walk(lowerThighLeft, 1.0F * globalSpeed, 0.6F * globalDegree, true, 1.0F, 0.5F, f, f1);
      this.walk(footLeft, 1.0F * globalSpeed, 0.6F * globalDegree, false, -1.5F, 0.85F, f, f1);
      this.walk(thighRight, 1.0F * globalSpeed, 0.7F * globalDegree, true, 0.0F, -0.4F, f, f1);
      this.walk(lowerThighRight, 1.0F * globalSpeed, 0.6F * globalDegree, false, 1.0F, 0.5F, f, f1);
      this.walk(footRight, 1.0F * globalSpeed, 0.6F * globalDegree, true, -1.5F, 0.85F, f, f1);
      this.walk(armLeft, 1.0F * globalSpeed, 0.7F * globalDegree, true, frontOffset + 0.0F, -0.2F, f, f1);
      this.walk(lowerArmLeft, 1.0F * globalSpeed, 0.6F * globalDegree, true, frontOffset + 1.0F, -0.2F, f, f1);
      this.walk(handLeft, 1.0F * globalSpeed, 0.6F * globalDegree, false, frontOffset + 2.0F, 0.8F, f, f1);
      this.walk(armRight, 1.0F * globalSpeed, 0.7F * globalDegree, false, frontOffset + 0.0F, -0.2F, f, f1);
      this.walk(lowerArmRight, 1.0F * globalSpeed, 0.6F * globalDegree, false, frontOffset + 1.0F, -0.2F, f, f1);
      this.walk(handRight, 1.0F * globalSpeed, 0.6F * globalDegree, true, frontOffset + 2.0F, 0.8F, f, f1);
      int ticksExisted = entity.tickCount;
      this.chainWave(this.tailParts, globalSpeed * 0.25F, globalHeight * 1.0F, 3.0D, (float)ticksExisted, 0.1F);
      this.chainWave(this.neckParts, globalSpeed * 0.25F, globalHeight * 0.25F, -4.0D, (float)ticksExisted, 0.1F);
      entity.tailBuffer.applyChainSwingBuffer(this.tailParts);
   }

   public void resetPose() {
      this.hips.resetToDefaultPose();
      this.toplegleft.resetToDefaultPose();
      this.toplegright.resetToDefaultPose();
      this.tail1.resetToDefaultPose();
      this.body.resetToDefaultPose();
      this.tail2.resetToDefaultPose();
      this.tail3.resetToDefaultPose();
      this.tail4.resetToDefaultPose();
      this.tail5.resetToDefaultPose();
      this.tail6.resetToDefaultPose();
      this.tail7.resetToDefaultPose();
      this.tail8.resetToDefaultPose();
      this.tail9.resetToDefaultPose();
      this.tail10.resetToDefaultPose();
      this.neck1.resetToDefaultPose();
      this.Stomach.resetToDefaultPose();
      this.frontlefttopleg.resetToDefaultPose();
      this.frontrighttopleg.resetToDefaultPose();
      this.neck2.resetToDefaultPose();
      this.neck3.resetToDefaultPose();
      this.neck4.resetToDefaultPose();
      this.neck5.resetToDefaultPose();
      this.neck6.resetToDefaultPose();
      this.neck7.resetToDefaultPose();
      this.neck8.resetToDefaultPose();
      this.neck9.resetToDefaultPose();
      this.neck10.resetToDefaultPose();
      this.neck11.resetToDefaultPose();
      this.Head.resetToDefaultPose();
      this.UpperJaw.resetToDefaultPose();
      this.LowerJaw.resetToDefaultPose();
      this.HeadSlope.resetToDefaultPose();
      this.bottomfrontleftleg.resetToDefaultPose();
      this.frontleftfoot.resetToDefaultPose();
      this.bottomfrontrightleg.resetToDefaultPose();
      this.frontrightfoot.resetToDefaultPose();
      this.bottomlegleft.resetToDefaultPose();
      this.leftbackfoot.resetToDefaultPose();
      this.bottomlegright.resetToDefaultPose();
      this.rightbackfoot.resetToDefaultPose();
   }

   public void animate(IAnimatedEntity entity, float f, float f1, float f2, float f3, float f4, float f5) {
      this.animator.update(entity);
      this.setRotationAngles(f, f1, f2, f3, f4, f5, (EntityMamenchisaurus)entity);
   }

   public void setRotateAngle(MowzieModelRenderer modelRenderer, float x, float y, float z) {
      modelRenderer.rotateAngleX = x;
      modelRenderer.rotateAngleY = y;
      modelRenderer.rotateAngleZ = z;
   }
}
