package net.ilexiconn.jurassicraft.client.model.entity;

import net.ilexiconn.llibrary.client.model.tools.ResettableModelRenderer;

import net.ilexiconn.llibrary.client.model.tools.AdvancedModelBase;
import net.minecraft.world.entity.Entity;
import net.minecraft.util.Mth;
import net.ilexiconn.jurassicraft.common.api.IAnimatedEntity;
import net.ilexiconn.jurassicraft.client.model.animation.Animator;

public class ModelUintatherium extends AdvancedModelBase {

   private Animator animator;
   public static final float PI = 3.1415927F;
   ResettableModelRenderer leftbackleg1;
   ResettableModelRenderer leftbackleg2;
   ResettableModelRenderer leftbackleg3;
   ResettableModelRenderer leftbackleg4;
   ResettableModelRenderer rightbackleg1;
   ResettableModelRenderer rightbackleg2;
   ResettableModelRenderer rightbackleg3;
   ResettableModelRenderer rightbackleg4;
   ResettableModelRenderer leftfrontleg1;
   ResettableModelRenderer leftfrontleg2;
   ResettableModelRenderer leftfrontleg3;
   ResettableModelRenderer leftfrontleg4;
   ResettableModelRenderer rightfrontleg1;
   ResettableModelRenderer rightfrontleg2;
   ResettableModelRenderer rightfrontleg3;
   ResettableModelRenderer rightfrontleg4;
   ResettableModelRenderer upperfrontbody;
   ResettableModelRenderer bottomfrontbody;
   ResettableModelRenderer middlebody;
   ResettableModelRenderer upperbackbody;
   ResettableModelRenderer bottombackbody;
   ResettableModelRenderer neck;
   ResettableModelRenderer head;
   ResettableModelRenderer snout;
   ResettableModelRenderer mouth;
   ResettableModelRenderer rightupperhorn;
   ResettableModelRenderer leftupperhorn;
   ResettableModelRenderer rightmiddlehorn;
   ResettableModelRenderer leftmiddlehorn;
   ResettableModelRenderer rightbottomhorn;
   ResettableModelRenderer leftbottomhorn;
   ResettableModelRenderer lefttooth;
   ResettableModelRenderer righttooth;
   ResettableModelRenderer tail1;
   ResettableModelRenderer tail2;
   ResettableModelRenderer tail3;
   ResettableModelRenderer leftear;
   ResettableModelRenderer rightear;


   public ModelUintatherium() {
      this.textureWidth = 128;
      this.textureHeight = 128;
      this.animator = new Animator(this);
      this.leftbackleg1 = new ResettableModelRenderer(this, 28, 65);
      this.leftbackleg1.addBox(-5.0F, -5.5F, -4.0F, 8, 11, 10);
      this.leftbackleg1.setRotationPoint(7.0F, 7.0F, 11.0F);
      this.leftbackleg1.setTextureSize(128, 128);
      this.leftbackleg1.mirror = true;
      this.setRotation(this.leftbackleg1, -0.2617994F, 0.0F, 0.0F);
      this.leftbackleg2 = new ResettableModelRenderer(this, 32, 86);
      this.leftbackleg2.addBox(-2.5F, 4.0F, -4.0F, 5, 5, 7);
      this.leftbackleg2.setRotationPoint(7.0F, 8.0F, 11.0F);
      this.leftbackleg2.setTextureSize(128, 128);
      this.leftbackleg2.mirror = true;
      this.setRotation(this.leftbackleg2, -0.2617994F, 0.0F, 0.0F);
      this.leftbackleg3 = new ResettableModelRenderer(this, 64, 65);
      this.leftbackleg3.addBox(-2.0F, 5.5F, -8.5F, 4, 7, 4);
      this.leftbackleg3.setRotationPoint(7.0F, 7.0F, 11.0F);
      this.leftbackleg3.setTextureSize(128, 128);
      this.leftbackleg3.mirror = true;
      this.setRotation(this.leftbackleg3, 0.4363323F, 0.0F, 0.0F);
      this.leftbackleg4 = new ResettableModelRenderer(this, 88, 38);
      this.leftbackleg4.addBox(-2.0F, 13.0F, 0.0F, 4, 4, 4);
      this.leftbackleg4.setRotationPoint(7.0F, 7.0F, 8.0F);
      this.leftbackleg4.setTextureSize(128, 128);
      this.leftbackleg4.mirror = true;
      this.setRotation(this.leftbackleg4, 0.0F, 0.0F, 0.0F);
      this.rightbackleg1 = new ResettableModelRenderer(this, 28, 65);
      this.rightbackleg1.addBox(-3.0F, -5.5F, -4.0F, 8, 11, 10);
      this.rightbackleg1.setRotationPoint(-7.0F, 7.0F, 11.0F);
      this.rightbackleg1.setTextureSize(128, 128);
      this.rightbackleg1.mirror = true;
      this.setRotation(this.rightbackleg1, -0.2617994F, 0.0F, 0.0F);
      this.rightbackleg2 = new ResettableModelRenderer(this, 32, 86);
      this.rightbackleg2.addBox(-2.5F, 4.0F, -4.0F, 5, 5, 7);
      this.rightbackleg2.setRotationPoint(-7.044445F, 8.0F, 11.0F);
      this.rightbackleg2.setTextureSize(128, 128);
      this.rightbackleg2.mirror = true;
      this.setRotation(this.rightbackleg2, -0.2617994F, 0.0F, 0.0F);
      this.rightbackleg3 = new ResettableModelRenderer(this, 64, 65);
      this.rightbackleg3.addBox(-2.033333F, 5.5F, -8.5F, 4, 7, 4);
      this.rightbackleg3.setRotationPoint(-7.0F, 7.0F, 11.0F);
      this.rightbackleg3.setTextureSize(128, 128);
      this.rightbackleg3.mirror = true;
      this.setRotation(this.rightbackleg3, 0.4363323F, 0.0F, 0.0F);
      this.rightbackleg4 = new ResettableModelRenderer(this, 88, 38);
      this.rightbackleg4.addBox(-2.0F, 13.0F, 0.0F, 4, 4, 4);
      this.rightbackleg4.setRotationPoint(-7.0F, 7.0F, 8.0F);
      this.rightbackleg4.setTextureSize(128, 128);
      this.rightbackleg4.mirror = true;
      this.setRotation(this.rightbackleg4, 0.0F, 0.0F, 0.0F);
      this.leftfrontleg1 = new ResettableModelRenderer(this, 0, 68);
      this.leftfrontleg1.addBox(-4.0F, -5.0F, -2.0F, 6, 10, 8);
      this.leftfrontleg1.setRotationPoint(7.0F, 7.0F, -10.0F);
      this.leftfrontleg1.setTextureSize(128, 128);
      this.leftfrontleg1.mirror = true;
      this.setRotation(this.leftfrontleg1, 0.17453292F, 0.0F, 0.0F);
      this.leftfrontleg2 = new ResettableModelRenderer(this, 0, 86);
      this.leftfrontleg2.addBox(-2.5F, 4.0F, -1.5F, 4, 7, 4);
      this.leftfrontleg2.setRotationPoint(7.0F, 7.0F, -10.0F);
      this.leftfrontleg2.setTextureSize(128, 128);
      this.leftfrontleg2.mirror = true;
      this.setRotation(this.leftfrontleg2, 0.4363323F, 0.0F, 0.0F);
      this.leftfrontleg3 = new ResettableModelRenderer(this, 16, 86);
      this.leftfrontleg3.addBox(-2.5F, 6.5F, 4.0F, 4, 6, 4);
      this.leftfrontleg3.setRotationPoint(7.0F, 7.0F, -10.0F);
      this.leftfrontleg3.setTextureSize(128, 128);
      this.leftfrontleg3.mirror = true;
      this.setRotation(this.leftfrontleg3, -0.2617994F, 0.0F, 0.0F);
      this.leftfrontleg4 = new ResettableModelRenderer(this, 88, 38);
      this.leftfrontleg4.addBox(-2.5F, 13.0F, 0.5F, 4, 4, 4);
      this.leftfrontleg4.setRotationPoint(7.0F, 7.0F, -10.0F);
      this.leftfrontleg4.setTextureSize(128, 128);
      this.leftfrontleg4.mirror = true;
      this.setRotation(this.leftfrontleg4, 0.0F, 0.0F, 0.0F);
      this.rightfrontleg1 = new ResettableModelRenderer(this, 0, 68);
      this.rightfrontleg1.addBox(-2.0F, -5.0F, -2.0F, 6, 10, 8);
      this.rightfrontleg1.setRotationPoint(-7.0F, 7.0F, -10.0F);
      this.rightfrontleg1.setTextureSize(128, 128);
      this.rightfrontleg1.mirror = true;
      this.setRotation(this.rightfrontleg1, 0.17453292F, 0.0F, 0.0F);
      this.rightfrontleg2 = new ResettableModelRenderer(this, 0, 86);
      this.rightfrontleg2.addBox(-1.5F, 4.0F, -1.5F, 4, 7, 4);
      this.rightfrontleg2.setRotationPoint(-7.0F, 7.0F, -10.0F);
      this.rightfrontleg2.setTextureSize(128, 128);
      this.rightfrontleg2.mirror = true;
      this.setRotation(this.rightfrontleg2, 0.4363323F, 0.0F, 0.0F);
      this.rightfrontleg3 = new ResettableModelRenderer(this, 16, 86);
      this.rightfrontleg3.addBox(-1.5F, 6.5F, 4.0F, 4, 6, 4);
      this.rightfrontleg3.setRotationPoint(-7.0F, 7.0F, -10.0F);
      this.rightfrontleg3.setTextureSize(128, 128);
      this.rightfrontleg3.mirror = true;
      this.setRotation(this.rightfrontleg3, -0.2617994F, 0.0F, 0.0F);
      this.rightfrontleg4 = new ResettableModelRenderer(this, 88, 38);
      this.rightfrontleg4.addBox(-1.5F, 13.0F, 0.5F, 4, 4, 4);
      this.rightfrontleg4.setRotationPoint(-7.0F, 7.0F, -10.0F);
      this.rightfrontleg4.setTextureSize(128, 128);
      this.rightfrontleg4.mirror = true;
      this.setRotation(this.rightfrontleg4, 0.0F, 0.0F, 0.0F);
      this.upperfrontbody = new ResettableModelRenderer(this, 66, 0);
      this.upperfrontbody.addBox(-7.5F, -6.0F, -14.5F, 15, 12, 10);
      this.upperfrontbody.setRotationPoint(0.0F, 5.0F, 0.0F);
      this.upperfrontbody.setTextureSize(128, 128);
      this.upperfrontbody.mirror = true;
      this.setRotation(this.upperfrontbody, 0.1745329F, 0.0F, 0.0F);
      this.bottomfrontbody = new ResettableModelRenderer(this, 66, 22);
      this.bottomfrontbody.addBox(-7.0F, 4.2F, -11.5F, 14, 6, 10);
      this.bottomfrontbody.setRotationPoint(0.0F, 5.0F, 0.0F);
      this.bottomfrontbody.setTextureSize(128, 128);
      this.bottomfrontbody.mirror = true;
      this.setRotation(this.bottomfrontbody, -0.17453292F, 0.0F, 0.0F);
      this.middlebody = new ResettableModelRenderer(this, 0, 0);
      this.middlebody.addBox(-7.5F, -5.0F, -6.0F, 15, 15, 18);
      this.middlebody.setRotationPoint(0.0F, 5.0F, 0.0F);
      this.middlebody.setTextureSize(128, 128);
      this.middlebody.mirror = true;
      this.setRotation(this.middlebody, 0.0F, 0.0F, 0.0F);
      this.upperbackbody = new ResettableModelRenderer(this, 0, 33);
      this.upperbackbody.addBox(-7.0F, -6.0F, 10.0F, 14, 11, 8);
      this.upperbackbody.setRotationPoint(0.0F, 5.0F, 0.0F);
      this.upperbackbody.setTextureSize(128, 128);
      this.upperbackbody.mirror = true;
      this.setRotation(this.upperbackbody, -0.17453292F, 0.0F, 0.0F);
      this.bottombackbody = new ResettableModelRenderer(this, 44, 38);
      this.bottombackbody.addBox(-7.0F, 7.0F, 10.0F, 14, 2, 6);
      this.bottombackbody.setRotationPoint(0.0F, 5.0F, 0.0F);
      this.bottombackbody.setTextureSize(128, 128);
      this.bottombackbody.mirror = true;
      this.setRotation(this.bottombackbody, 0.0F, 0.0F, 0.0F);
      this.neck = new ResettableModelRenderer(this, 86, 46);
      this.neck.addBox(-4.0F, -2.0F, -1.5F, 8, 6, 5);
      this.neck.setRotationPoint(0.0F, 3.0F, -15.0F);
      this.neck.setTextureSize(128, 128);
      this.neck.mirror = true;
      this.setRotation(this.neck, 0.0F, 0.0F, 0.0F);
      this.head = new ResettableModelRenderer(this, 0, 52);
      this.head.addBox(-4.5F, -3.0F, -8.0F, 9, 8, 8);
      this.head.setRotationPoint(0.0F, 3.0F, -15.0F);
      this.head.setTextureSize(128, 128);
      this.head.mirror = true;
      this.setRotation(this.head, 0.4886922F, 0.0F, 0.0F);
      this.snout = new ResettableModelRenderer(this, 34, 52);
      this.snout.addBox(-3.988889F, -5.0F, -14.5F, 8, 5, 8);
      this.snout.setRotationPoint(0.0F, 3.0F, -15.0F);
      this.snout.setTextureSize(128, 128);
      this.snout.mirror = true;
      this.setRotation(this.snout, 0.7853982F, 0.0F, 0.0F);
      this.mouth = new ResettableModelRenderer(this, 58, 46);
      this.mouth.addBox(-3.0F, -0.8F, -13.5F, 6, 3, 8);
      this.mouth.setRotationPoint(0.0F, 4.0F, -15.0F);
      this.mouth.setTextureSize(128, 128);
      this.mouth.mirror = true;
      this.setRotation(this.mouth, 0.715585F, 0.0F, 0.0F);
      this.rightupperhorn = new ResettableModelRenderer(this, 120, 0);
      this.rightupperhorn.addBox(-2.711111F, -6.5F, -3.0F, 1, 3, 1);
      this.rightupperhorn.setRotationPoint(0.0F, 3.0F, -15.0F);
      this.rightupperhorn.setTextureSize(128, 128);
      this.rightupperhorn.mirror = true;
      this.setRotation(this.rightupperhorn, 0.5759587F, 0.0F, -0.17453292F);
      this.leftupperhorn = new ResettableModelRenderer(this, 120, 0);
      this.leftupperhorn.addBox(2.288889F, -6.5F, -3.0F, 1, 3, 1);
      this.leftupperhorn.setRotationPoint(0.0F, 3.0F, -15.0F);
      this.leftupperhorn.setTextureSize(128, 128);
      this.leftupperhorn.mirror = true;
      this.setRotation(this.leftupperhorn, 0.5759587F, 0.0F, 0.17453292F);
      this.rightmiddlehorn = new ResettableModelRenderer(this, 120, 0);
      this.rightmiddlehorn.addBox(-3.0F, -7.5F, -8.0F, 1, 3, 1);
      this.rightmiddlehorn.setRotationPoint(0.0F, 3.0F, -15.0F);
      this.rightmiddlehorn.setTextureSize(128, 128);
      this.rightmiddlehorn.mirror = true;
      this.setRotation(this.rightmiddlehorn, 0.7853982F, 0.0F, -0.17453292F);
      this.leftmiddlehorn = new ResettableModelRenderer(this, 120, 0);
      this.leftmiddlehorn.addBox(2.0F, -7.5F, -8.0F, 1, 3, 1);
      this.leftmiddlehorn.setRotationPoint(0.0F, 3.0F, -15.0F);
      this.leftmiddlehorn.setTextureSize(128, 128);
      this.leftmiddlehorn.mirror = true;
      this.setRotation(this.leftmiddlehorn, 0.7853982F, 0.0F, 0.17453292F);
      this.rightbottomhorn = new ResettableModelRenderer(this, 116, 0);
      this.rightbottomhorn.addBox(-3.0F, -6.5F, -13.5F, 1, 2, 1);
      this.rightbottomhorn.setRotationPoint(0.0F, 3.0F, -15.0F);
      this.rightbottomhorn.setTextureSize(128, 128);
      this.rightbottomhorn.mirror = true;
      this.setRotation(this.rightbottomhorn, 0.7504916F, 0.0F, -0.17453292F);
      this.leftbottomhorn = new ResettableModelRenderer(this, 116, 0);
      this.leftbottomhorn.addBox(2.0F, -6.5F, -13.5F, 1, 2, 1);
      this.leftbottomhorn.setRotationPoint(0.0F, 3.0F, -15.0F);
      this.leftbottomhorn.setTextureSize(128, 128);
      this.leftbottomhorn.mirror = true;
      this.setRotation(this.leftbottomhorn, 0.7504916F, 0.0F, 0.17453292F);
      this.lefttooth = new ResettableModelRenderer(this, 116, 4);
      this.lefttooth.addBox(2.5F, 2.5F, -11.5F, 1, 2, 1);
      this.lefttooth.setRotationPoint(0.0F, 3.0F, -15.0F);
      this.lefttooth.setTextureSize(128, 128);
      this.lefttooth.mirror = true;
      this.setRotation(this.lefttooth, 0.5235988F, 0.0F, 0.0F);
      this.righttooth = new ResettableModelRenderer(this, 116, 4);
      this.righttooth.addBox(-3.5F, 2.5F, -11.5F, 1, 2, 1);
      this.righttooth.setRotationPoint(0.0F, 3.0F, -15.0F);
      this.righttooth.setTextureSize(128, 128);
      this.righttooth.mirror = true;
      this.setRotation(this.righttooth, 0.5235988F, 0.0F, 0.0F);
      this.tail1 = new ResettableModelRenderer(this, 85, 60);
      this.tail1.addBox(-0.5F, -0.5F, 0.0F, 1, 1, 4);
      this.tail1.setRotationPoint(0.0F, 4.0F, 17.97778F);
      this.tail1.setTextureSize(128, 128);
      this.tail1.mirror = true;
      this.setRotation(this.tail1, -0.7853982F, 0.0F, 0.0F);
      this.tail2 = new ResettableModelRenderer(this, 85, 65);
      this.tail2.addBox(-0.5F, -2.6F, 3.0F, 1, 1, 4);
      this.tail2.setRotationPoint(0.0F, 4.0F, 18.0F);
      this.tail2.setTextureSize(128, 128);
      this.tail2.mirror = true;
      this.setRotation(this.tail2, -1.3962634F, 0.0F, 0.0F);
      this.tail3 = new ResettableModelRenderer(this, 85, 70);
      this.tail3.addBox(-1.0F, -2.0F, 6.0F, 2, 0, 3);
      this.tail3.setRotationPoint(0.0F, 4.0F, 18.0F);
      this.tail3.setTextureSize(128, 128);
      this.tail3.mirror = true;
      this.setRotation(this.tail3, -1.3962634F, 0.0F, 0.0F);
      this.leftear = new ResettableModelRenderer(this, 100, 60);
      this.leftear.addBox(3.0F, -4.0F, -3.5F, 2, 3, 1);
      this.leftear.setRotationPoint(0.0F, 3.0F, -15.0F);
      this.leftear.setTextureSize(128, 128);
      this.leftear.mirror = true;
      this.setRotation(this.leftear, -0.17453292F, -0.17453292F, 0.17453292F);
      this.rightear = new ResettableModelRenderer(this, 106, 60);
      this.rightear.addBox(-5.0F, -4.0F, -3.5F, 2, 3, 1);
      this.rightear.setRotationPoint(0.0F, 3.0F, -15.0F);
      this.rightear.setTextureSize(128, 128);
      this.rightear.mirror = true;
      this.setRotation(this.rightear, -0.17453292F, 0.17453292F, -0.17453292F);
      this.leftbackleg1.savefirstParameters();
      this.leftbackleg2.savefirstParameters();
      this.leftbackleg3.savefirstParameters();
      this.leftbackleg4.savefirstParameters();
      this.rightbackleg1.savefirstParameters();
      this.rightbackleg2.savefirstParameters();
      this.rightbackleg3.savefirstParameters();
      this.rightbackleg4.savefirstParameters();
      this.leftfrontleg1.savefirstParameters();
      this.leftfrontleg2.savefirstParameters();
      this.leftfrontleg3.savefirstParameters();
      this.leftfrontleg4.savefirstParameters();
      this.rightfrontleg1.savefirstParameters();
      this.rightfrontleg2.savefirstParameters();
      this.rightfrontleg3.savefirstParameters();
      this.rightfrontleg4.savefirstParameters();
      this.upperfrontbody.savefirstParameters();
      this.bottomfrontbody.savefirstParameters();
      this.middlebody.savefirstParameters();
      this.upperbackbody.savefirstParameters();
      this.bottombackbody.savefirstParameters();
      this.neck.savefirstParameters();
      this.head.savefirstParameters();
      this.snout.savefirstParameters();
      this.mouth.savefirstParameters();
      this.rightupperhorn.savefirstParameters();
      this.leftupperhorn.savefirstParameters();
      this.rightmiddlehorn.savefirstParameters();
      this.leftmiddlehorn.savefirstParameters();
      this.rightbottomhorn.savefirstParameters();
      this.leftbottomhorn.savefirstParameters();
      this.lefttooth.savefirstParameters();
      this.righttooth.savefirstParameters();
      this.tail1.savefirstParameters();
      this.tail2.savefirstParameters();
      this.tail3.savefirstParameters();
      this.leftear.savefirstParameters();
      this.rightear.savefirstParameters();
   }

   public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
      super.render(entity, f, f1, f2, f3, f4, f5);
      this.animate(entity, f, f1, f2, f3, f4, f5);
      this.leftbackleg1.render(f5);
      this.leftbackleg2.render(f5);
      this.leftbackleg3.render(f5);
      this.leftbackleg4.render(f5);
      this.rightbackleg1.render(f5);
      this.rightbackleg2.render(f5);
      this.rightbackleg3.render(f5);
      this.rightbackleg4.render(f5);
      this.leftfrontleg1.render(f5);
      this.leftfrontleg2.render(f5);
      this.leftfrontleg3.render(f5);
      this.leftfrontleg4.render(f5);
      this.rightfrontleg1.render(f5);
      this.rightfrontleg2.render(f5);
      this.rightfrontleg3.render(f5);
      this.rightfrontleg4.render(f5);
      this.upperfrontbody.render(f5);
      this.bottomfrontbody.render(f5);
      this.middlebody.render(f5);
      this.upperbackbody.render(f5);
      this.bottombackbody.render(f5);
      this.neck.render(f5);
      this.head.render(f5);
      this.snout.render(f5);
      this.mouth.render(f5);
      this.rightupperhorn.render(f5);
      this.leftupperhorn.render(f5);
      this.rightmiddlehorn.render(f5);
      this.leftmiddlehorn.render(f5);
      this.rightbottomhorn.render(f5);
      this.leftbottomhorn.render(f5);
      this.lefttooth.render(f5);
      this.righttooth.render(f5);
      this.tail1.render(f5);
      this.tail2.render(f5);
      this.tail3.render(f5);
      this.leftear.render(f5);
      this.rightear.render(f5);
   }

   private void setRotation(ResettableModelRenderer model, float x, float y, float z) {
      model.rotateAngleX = x;
      model.rotateAngleY = y;
      model.rotateAngleZ = z;
   }

   public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
      super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
      this.upperbackbody.rotateAngleX = this.upperbackbody.firstRotateAngleX;
      this.upperbackbody.rotateAngleY = this.upperbackbody.firstRotateAngleY;
      this.upperbackbody.rotateAngleZ = this.upperbackbody.firstRotateAngleZ;
      this.head.rotateAngleX = f4 / 71.61972F + this.head.firstRotateAngleX;
      this.snout.rotateAngleX = f4 / 71.61972F + this.snout.firstRotateAngleX;
      this.mouth.rotateAngleX = f4 / 71.61972F + this.mouth.firstRotateAngleX;
      this.lefttooth.rotateAngleX = f4 / 71.61972F + this.lefttooth.firstRotateAngleX;
      this.righttooth.rotateAngleX = f4 / 71.61972F + this.righttooth.firstRotateAngleX;
      this.leftear.rotateAngleX = f4 / 71.61972F + this.leftear.firstRotateAngleX;
      this.rightear.rotateAngleX = f4 / 71.61972F + this.rightear.firstRotateAngleX;
      this.rightupperhorn.rotateAngleX = f4 / 71.61972F + this.rightupperhorn.firstRotateAngleX;
      this.leftupperhorn.rotateAngleX = f4 / 71.61972F + this.leftupperhorn.firstRotateAngleX;
      this.rightmiddlehorn.rotateAngleX = f4 / 71.61972F + this.rightmiddlehorn.firstRotateAngleX;
      this.leftmiddlehorn.rotateAngleX = f4 / 71.61972F + this.leftmiddlehorn.firstRotateAngleX;
      this.rightbottomhorn.rotateAngleX = f4 / 71.61972F + this.rightbottomhorn.firstRotateAngleX;
      this.leftbottomhorn.rotateAngleX = f4 / 71.61972F + this.leftbottomhorn.firstRotateAngleX;
      this.head.rotateAngleY = f3 / 71.61972F + this.head.firstRotateAngleY;
      this.snout.rotateAngleY = f3 / 71.61972F + this.snout.firstRotateAngleY;
      this.mouth.rotateAngleY = f3 / 71.61972F + this.mouth.firstRotateAngleY;
      this.lefttooth.rotateAngleY = f3 / 71.61972F + this.lefttooth.firstRotateAngleY;
      this.righttooth.rotateAngleY = f3 / 71.61972F + this.righttooth.firstRotateAngleY;
      this.leftear.rotateAngleY = f3 / 71.61972F + this.leftear.firstRotateAngleY;
      this.rightear.rotateAngleY = f3 / 71.61972F + this.rightear.firstRotateAngleY;
      this.rightupperhorn.rotateAngleY = f3 / 71.61972F + this.rightupperhorn.firstRotateAngleY;
      this.leftupperhorn.rotateAngleY = f3 / 71.61972F + this.leftupperhorn.firstRotateAngleY;
      this.rightmiddlehorn.rotateAngleY = f3 / 71.61972F + this.rightmiddlehorn.firstRotateAngleY;
      this.leftmiddlehorn.rotateAngleY = f3 / 71.61972F + this.leftmiddlehorn.firstRotateAngleY;
      this.rightbottomhorn.rotateAngleY = f3 / 71.61972F + this.rightbottomhorn.firstRotateAngleY;
      this.leftbottomhorn.rotateAngleY = f3 / 71.61972F + this.leftbottomhorn.firstRotateAngleY;
      this.rightupperhorn.rotateAngleZ = this.rightupperhorn.firstRotateAngleZ / 8.0F;
      this.leftupperhorn.rotateAngleZ = this.leftupperhorn.firstRotateAngleZ / 8.0F;
      this.rightmiddlehorn.rotateAngleZ = this.rightmiddlehorn.firstRotateAngleZ / 8.0F;
      this.leftmiddlehorn.rotateAngleZ = this.leftmiddlehorn.firstRotateAngleZ / 8.0F;
      this.rightbottomhorn.rotateAngleZ = this.rightbottomhorn.firstRotateAngleZ / 8.0F;
      this.leftbottomhorn.rotateAngleZ = this.leftbottomhorn.firstRotateAngleZ / 8.0F;
      this.leftbackleg1.rotateAngleX = Mth.cos(f * 0.6662F + 3.1415927F) * 1.0F * f1 + this.leftbackleg1.firstRotateAngleX;
      this.leftbackleg2.rotateAngleX = Mth.cos(f * 0.6662F + 3.1415927F) * 1.0F * f1 + this.leftbackleg2.firstRotateAngleX;
      this.leftbackleg3.rotateAngleX = Mth.cos(f * 0.6662F + 3.1415927F) * 1.0F * f1 + this.leftbackleg3.firstRotateAngleX;
      this.leftbackleg4.rotateAngleX = Mth.cos(f * 0.6662F + 3.1415927F) * 1.0F * f1 + this.leftbackleg4.firstRotateAngleX;
      this.rightbackleg1.rotateAngleX = Mth.cos(f * 0.6662F) * 1.0F * f1 + this.rightbackleg1.firstRotateAngleX;
      this.rightbackleg2.rotateAngleX = Mth.cos(f * 0.6662F) * 1.0F * f1 + this.rightbackleg2.firstRotateAngleX;
      this.rightbackleg3.rotateAngleX = Mth.cos(f * 0.6662F) * 1.0F * f1 + this.rightbackleg3.firstRotateAngleX;
      this.rightbackleg4.rotateAngleX = Mth.cos(f * 0.6662F) * 1.0F * f1 + this.rightbackleg4.firstRotateAngleX;
      this.leftfrontleg1.rotateAngleX = Mth.cos(f * 0.6662F) * 1.0F * f1 + this.leftfrontleg1.firstRotateAngleX;
      this.leftfrontleg2.rotateAngleX = Mth.cos(f * 0.6662F) * 1.0F * f1 + this.leftfrontleg2.firstRotateAngleX;
      this.leftfrontleg3.rotateAngleX = Mth.cos(f * 0.6662F) * 1.0F * f1 + this.leftfrontleg3.firstRotateAngleX;
      this.leftfrontleg4.rotateAngleX = Mth.cos(f * 0.6662F) * 1.0F * f1 + this.leftfrontleg4.firstRotateAngleX;
      this.rightfrontleg1.rotateAngleX = Mth.cos(f * 0.6662F + 3.1415927F) * 1.0F * f1 + this.rightfrontleg1.firstRotateAngleX;
      this.rightfrontleg2.rotateAngleX = Mth.cos(f * 0.6662F + 3.1415927F) * 1.0F * f1 + this.rightfrontleg2.firstRotateAngleX;
      this.rightfrontleg3.rotateAngleX = Mth.cos(f * 0.6662F + 3.1415927F) * 1.0F * f1 + this.rightfrontleg3.firstRotateAngleX;
      this.rightfrontleg4.rotateAngleX = Mth.cos(f * 0.6662F + 3.1415927F) * 1.0F * f1 + this.rightfrontleg4.firstRotateAngleX;
      this.tail1.rotateAngleX = 0.05F * Mth.sin(0.1F * f2 + f1) + this.tail1.firstRotateAngleX;
      this.tail2.rotateAngleX = 0.05F * Mth.sin(0.1F * f2 + f1) + this.tail2.firstRotateAngleX;
      this.tail3.rotateAngleX = 0.05F * Mth.sin(0.1F * f2 + f1) + this.tail3.firstRotateAngleX;
      this.tail1.rotateAngleY = 0.05F * Mth.sin(0.1F * f2 + f1) + this.tail1.firstRotateAngleY;
      this.tail2.rotateAngleY = 0.05F * Mth.sin(0.1F * f2 + f1) + this.tail2.firstRotateAngleY;
      this.tail3.rotateAngleY = 0.05F * Mth.sin(0.1F * f2 + f1) + this.tail3.firstRotateAngleY;
      this.tail1.rotateAngleZ = 0.05F * Mth.cos(0.1F * f2 + f1) + this.tail1.firstRotateAngleZ;
      this.tail2.rotateAngleZ = 0.05F * Mth.cos(0.1F * f2 + f1) + this.tail2.firstRotateAngleZ;
      this.tail3.rotateAngleZ = 0.05F * Mth.cos(0.1F * f2 + f1) + this.tail3.firstRotateAngleZ;
   }

   public void animate(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
      this.animator.update((IAnimatedEntity)entity);
      this.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
      this.animator.setAnimation(2);
      this.animator.startPhase(7);
      this.animator.rotate(this.head, 1.0471976F, 0.0F, 0.0F);
      this.animator.rotate(this.snout, 1.0471976F, 0.0F, 0.0F);
      this.animator.rotate(this.mouth, 1.0471976F, 0.0F, 0.0F);
      this.animator.rotate(this.rightupperhorn, 1.0471976F, 0.0F, 0.0F);
      this.animator.rotate(this.leftupperhorn, 1.0471976F, 0.0F, 0.0F);
      this.animator.rotate(this.rightmiddlehorn, 1.0471976F, 0.0F, 0.0F);
      this.animator.rotate(this.leftmiddlehorn, 1.0471976F, 0.0F, 0.0F);
      this.animator.rotate(this.rightbottomhorn, 1.0471976F, 0.0F, 0.0F);
      this.animator.rotate(this.leftbottomhorn, 1.0471976F, 0.0F, 0.0F);
      this.animator.rotate(this.lefttooth, 1.0471976F, 0.0F, 0.0F);
      this.animator.rotate(this.righttooth, 1.0471976F, 0.0F, 0.0F);
      this.animator.rotate(this.leftear, 1.0471976F, 0.0F, 0.0F);
      this.animator.rotate(this.rightear, 1.0471976F, 0.0F, 0.0F);
      this.animator.endPhase();
      this.animator.setStationaryPhase(3);
      this.animator.startPhase(3);
      this.animator.rotate(this.head, -1.5707964F, 0.0F, 0.0F);
      this.animator.rotate(this.snout, -1.5707964F, 0.0F, 0.0F);
      this.animator.rotate(this.mouth, -1.5707964F, 0.0F, 0.0F);
      this.animator.rotate(this.rightupperhorn, -1.5707964F, 0.0F, 0.0F);
      this.animator.rotate(this.leftupperhorn, -1.5707964F, 0.0F, 0.0F);
      this.animator.rotate(this.rightmiddlehorn, -1.5707964F, 0.0F, 0.0F);
      this.animator.rotate(this.leftmiddlehorn, -1.5707964F, 0.0F, 0.0F);
      this.animator.rotate(this.rightbottomhorn, -1.5707964F, 0.0F, 0.0F);
      this.animator.rotate(this.leftbottomhorn, -1.5707964F, 0.0F, 0.0F);
      this.animator.rotate(this.lefttooth, -1.5707964F, 0.0F, 0.0F);
      this.animator.rotate(this.righttooth, -1.5707964F, 0.0F, 0.0F);
      this.animator.rotate(this.leftear, -1.5707964F, 0.0F, 0.0F);
      this.animator.rotate(this.rightear, -1.5707964F, 0.0F, 0.0F);
      this.animator.endPhase();
      this.animator.resetPhase(2);
   }
}
